### ISSUE TITLE
Elide 5 - not create child entity instance of one-to-one relationship with shared primary key

### ISSUE THREAD

**Issue by thaingo** [yahoo/elide#1420]
## Expected Behavior
Given parent and child entities have one-to-one relationship with shared primary key. When client issues a POST request to create a parent entity instance, then it is also expected Elide to create a respective child entity instance via a logic within the parent's life cycle hook.

## Current Behavior
Elide 5 does create the child entity instance in-memory but does not persist it into database.
Elide 4 does NOT have this bug.

## Steps to Reproduce (for bugs)
1. checkout code from [here](https://github.com/thaingo/elide5-pr13-bug-hook)
2. issue POST request to create `Report` entity
3. check logging message or issue GET request to retrieve just created `Report` entity

## Your Environment
* Elide version used: Elide 5.0.0 - pr13
* Environment name and version (Java 1.8.0_152): 1.8.0_202
* Operating System and version: MacOS
* Link to your project: [here](https://github.com/thaingo/elide5-pr13-bug-hook)
* Link to relevant spectrum chat: [here](https://spectrum.chat/elide/elide-5-0/strange-error-occurred-in-elide-5-but-does-not-happen-in-elide-4~21c33699-51fd-4614-a7a3-edd20f7f528c)

**Comment by aklish** [comment]
Can you copy your POST request that you use to trigger the error?

**Comment by thaingo** [comment]
POST http://localhost:8080/api/v1/report
```json
{
    "data": {
        "type": "report",
        "attributes": {
            "name": "report 1",
            "description": "description of report 1"
        }
    }
}
```

**Comment by aklish** [comment]
I made the following edit to the life cycle hook:

```java
    @Override
    public void execute(
        Operation operation, Report report, RequestScope requestScope, Optional<ChangeSpec> optional) {
        // create Change
        Change change = new Change();
        change.setReport(report);

        //ADDED this line to trigger the cascade
        report.setChange(change);

        log.debug("Created Change entity at {} with id {} and ", change.getCreatedAt(), change.getId());
    }
```

From the logs, you can see the newly created change in the life cycle hook is now added to the DB:

08-07-2020 10:50:55.121 [task-1] DEBUG org.hibernate.SQL.logStatement - insert into Report (id, change_report_id, description, name) values (null, ?, ?, ?)
08-07-2020 10:50:55.139 [task-1] DEBUG example.hook.CreationHook.execute - Created Change entity at Wed Jul 08 10:50:55 CDT 2020 with id null and 
08-07-2020 10:50:55.164 [task-1] DEBUG org.hibernate.SQL.logStatement - insert into Change (createdAt, name, report_id) values (?, ?, ?)
08-07-2020 10:50:55.167 [task-1] DEBUG org.hibernate.SQL.logStatement - update Report set change_report_id=?, description=?, name=? where id=?

A few notes/caveats:
1. I only tried this on Elide 5 (not 4).
2. The stack trace in the spectrum chat looks like a bug of some kind - but it seems unrelated to this issue.  I could not reproduce that.

**Comment by thaingo** [comment]
Thanks @aklish for the help. I now understand more of the behavior in Elide 5.

Like I said in the spectrum, to reproduce, just issue a follow-up request like below and it would throw the error. That means if I issue request like (http Patch): `PATCH http://localhost:8080/api/v1/report/1/change` with body:
```
{
    "data": {
        "type": "change",
        "attributes": {
            "name": "change1"
        }
    }
}
```

Then you would get an error like this:

```java
09-07-2020 14:50:35.899 [task-6] DEBUG c.y.e.d.j.p.EntityManagerWrapper.logQuery - HQL Query: SELECT example_models_Report FROM example.models.Report AS example_models_Report  LEFT JOIN FETCH example_models_Report.change   WHERE example_models_Report.id IN (:id_1dae4427_0) 
09-07-2020 14:50:35.901 [task-6] ERROR com.yahoo.elide.Elide.handleRequest - Error or exception uncaught by Elide
java.lang.UnsupportedOperationException: class com.yahoo.elide.parsers.state.CollectionTerminalState
	at com.yahoo.elide.parsers.state.BaseState.handlePatch(BaseState.java:141)
	at com.yahoo.elide.parsers.state.StateContext.handlePatch(StateContext.java:115)
	at com.yahoo.elide.parsers.PatchVisitor.visitQuery(PatchVisitor.java:33)
	at com.yahoo.elide.parsers.PatchVisitor.visitQuery(PatchVisitor.java:20)
	at com.yahoo.elide.generated.parsers.CoreParser$QueryContext.accept(CoreParser.java:568)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46)
	at com.yahoo.elide.generated.parsers.CoreBaseVisitor.visitStart(CoreBaseVisitor.java:20)
	at com.yahoo.elide.parsers.BaseVisitor.visitStart(BaseVisitor.java:49)
	at com.yahoo.elide.parsers.BaseVisitor.visitStart(BaseVisitor.java:35)
	at com.yahoo.elide.generated.parsers.CoreParser$StartContext.accept(CoreParser.java:117)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
	at com.yahoo.elide.Elide.visit(Elide.java:264)
	at com.yahoo.elide.Elide.lambda$patch$4(Elide.java:233)
	at com.yahoo.elide.Elide.handleRequest(Elide.java:288)
	at com.yahoo.elide.Elide.patch(Elide.java:237)
	at com.yahoo.elide.spring.controllers.JsonApiController$3.call(JsonApiController.java:109)
	at com.yahoo.elide.spring.controllers.JsonApiController$3.call(JsonApiController.java:105)
	at org.springframework.web.context.request.async.WebAsyncManager.lambda$startCallableProcessing$4(WebAsyncManager.java:337)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2020-07-09 14:50:35.901 ERROR 13762 --- [         task-6] com.yahoo.elide.Elide                    : Error or exception uncaught by Elide

java.lang.UnsupportedOperationException: class com.yahoo.elide.parsers.state.CollectionTerminalState
	at com.yahoo.elide.parsers.state.BaseState.handlePatch(BaseState.java:141)
	at com.yahoo.elide.parsers.state.StateContext.handlePatch(StateContext.java:115)
	at com.yahoo.elide.parsers.PatchVisitor.visitQuery(PatchVisitor.java:33)
	at com.yahoo.elide.parsers.PatchVisitor.visitQuery(PatchVisitor.java:20)
	at com.yahoo.elide.generated.parsers.CoreParser$QueryContext.accept(CoreParser.java:568)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46)
	at com.yahoo.elide.generated.parsers.CoreBaseVisitor.visitStart(CoreBaseVisitor.java:20)
	at com.yahoo.elide.parsers.BaseVisitor.visitStart(BaseVisitor.java:49)
	at com.yahoo.elide.parsers.BaseVisitor.visitStart(BaseVisitor.java:35)
	at com.yahoo.elide.generated.parsers.CoreParser$StartContext.accept(CoreParser.java:117)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
	at com.yahoo.elide.Elide.visit(Elide.java:264)
	at com.yahoo.elide.Elide.lambda$patch$4(Elide.java:233)
	at com.yahoo.elide.Elide.handleRequest(Elide.java:288)
	at com.yahoo.elide.Elide.patch(Elide.java:237)
	at com.yahoo.elide.spring.controllers.JsonApiController$3.call(JsonApiController.java:109)
	at com.yahoo.elide.spring.controllers.JsonApiController$3.call(JsonApiController.java:105)
	at org.springframework.web.context.request.async.WebAsyncManager.lambda$startCallableProcessing$4(WebAsyncManager.java:337)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

2020-07-09 14:50:35.910  WARN 13762 --- [ qtp98801744-27] org.eclipse.jetty.server.HttpChannel     : /api/v1/report/1/change

org.springframework.web.util.NestedServletException: Request processing failed; nested exception is java.lang.UnsupportedOperationException: class com.yahoo.elide.parsers.state.CollectionTerminalState
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1014)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:880)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:590)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:763)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1631)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:320)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:115)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:90)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:118)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:84)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:158)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:103)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:103)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:215)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:358)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:271)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1618)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:549)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:602)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1610)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1363)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:489)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1580)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1278)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.RequestLogHandler.handle(RequestLogHandler.java:54)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handleAsync(Server.java:543)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$2(HttpChannel.java:391)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:547)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:391)
	at org.eclipse.jetty.server.HttpChannel.run(HttpChannel.java:335)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.UnsupportedOperationException: class com.yahoo.elide.parsers.state.CollectionTerminalState
	at com.yahoo.elide.parsers.state.BaseState.handlePatch(BaseState.java:141)
	at com.yahoo.elide.parsers.state.StateContext.handlePatch(StateContext.java:115)
	at com.yahoo.elide.parsers.PatchVisitor.visitQuery(PatchVisitor.java:33)
	at com.yahoo.elide.parsers.PatchVisitor.visitQuery(PatchVisitor.java:20)
	at com.yahoo.elide.generated.parsers.CoreParser$QueryContext.accept(CoreParser.java:568)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46)
	at com.yahoo.elide.generated.parsers.CoreBaseVisitor.visitStart(CoreBaseVisitor.java:20)
	at com.yahoo.elide.parsers.BaseVisitor.visitStart(BaseVisitor.java:49)
	at com.yahoo.elide.parsers.BaseVisitor.visitStart(BaseVisitor.java:35)
	at com.yahoo.elide.generated.parsers.CoreParser$StartContext.accept(CoreParser.java:117)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
	at com.yahoo.elide.Elide.visit(Elide.java:264)
	at com.yahoo.elide.Elide.lambda$patch$4(Elide.java:233)
	at com.yahoo.elide.Elide.handleRequest(Elide.java:288)
	at com.yahoo.elide.Elide.patch(Elide.java:237)
	at com.yahoo.elide.spring.controllers.JsonApiController$3.call(JsonApiController.java:109)
	at com.yahoo.elide.spring.controllers.JsonApiController$3.call(JsonApiController.java:105)
	at org.springframework.web.context.request.async.WebAsyncManager.lambda$startCallableProcessing$4(WebAsyncManager.java:337)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 1 common frames omitted

0:0:0:0:0:0:0:1 - - [09/Jul/2020:14:50:35 +0700] "GET /api/v1/report/1/change HTTP/1.1" 500 335
```

Now if **your change is applied** to trigger the cascade, then Elide would verify the request and throw an **expected** error:
```java
{
"errors":[
{"detail":"Bad Request Body&#39;Id in response body does not match requested id to update from path&#39;"}
]
}```

I guess Elide 5 assumes the entity instance is already persisted. Some improvement might need to be done for ```com.yahoo.elide.parsers.state.BaseState.handlePatch```
