### ISSUE TITLE
Problems Building Project on Windows 10

### ISSUE THREAD

**Issue by kiangtengl** [yahoo/elide#157]
I think that there might be some problems with regards to the pom.xml file that causes the build process to fail on Windows 10. I've managed to build the project sucessfully on Ubuntu 14.04, but have had no luck so far on Windows.

The command run was: `mvn verify -Dmaven.test.skip=true -e`

```
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Elide Data Store: Hibernate 5 2.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Elide: Parent Pom .................................. SUCCESS [  2.703 s]
[INFO] Elide: Core ........................................ SUCCESS [ 42.211 s]
[INFO] Elide Data Store: Parent Pom ....................... SUCCESS [  0.406 s]
[INFO] Elide Data Store: Hibernate Common ................. SUCCESS [  4.112 s]
[INFO] Elide: Integration Test Library .................... SUCCESS [  2.280 s]
[INFO] Elide Data Store: Hibernate 5 ...................... FAILURE [  0.156 s]
[INFO] Elide Data Store: Hibernate 3 ...................... SKIPPED
[INFO] Elide Data Store: In-Memory ........................ SKIPPED
[INFO] Elide Data Store: Multiplex Library ................ SKIPPED
[INFO] Elide Example: Parent Pom .......................... SKIPPED
[INFO] Elide Example: Persistence API with MySQL .......... SKIPPED
[INFO] Elide Example: Hibernate 3 API with MySQL .......... SKIPPED
[INFO] Elide Example: Persistence API with Security ....... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 52.191 s
[INFO] Finished at: 2016-02-26T18:15:44-06:00
[INFO] Final Memory: 49M/511M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project elide-datastore-hibernate5: Could not resolve dependencies for project com.yahoo.elide:elide-datastore-hibernate5:jar:2.0.0-SNAPSHOT: The following artifacts could not be resolved: com.yahoo.elide:elide-datastore-hibernate:jar:tests:2.0.0-SNAPSHOT, com.yahoo.elide:elide-integration-tests:jar:tests:2.0.0-SNAPSHOT: Could not find artifact com.yahoo.elide:elide-datastore-hibernate:jar:tests:2.0.0-SNAPSHOT -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project elide-datastore-hibernate5: Could not resolve dependencies for project com.yahoo.elide:elide-datastore-hibernate5:jar:2.0.0-SNAPSHOT: The following artifacts could not be resolved: com.yahoo.elide:elide-datastore-hibernate:jar:tests:2.0.0-SNAPSHOT, com.yahoo.elide:elide-integration-tests:jar:tests:2.0.0-SNAPSHOT: Could not find artifact com.yahoo.elide:elide-datastore-hibernate:jar:tests:2.0.0-SNAPSHOT
        at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:221)
        at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.resolveProjectDependencies(LifecycleDependencyResolver.java:127)
        at org.apache.maven.lifecycle.internal.MojoExecutor.ensureDependenciesAreResolved(MojoExecutor.java:245)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:199)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.project.DependencyResolutionException: Could not resolve dependencies for project com.yahoo.elide:elide-datastore-hibernate5:jar:2.0.0-SNAPSHOT: The following artifacts could not be resolved: com.yahoo.elide:elide-datastore-hibernate:jar:tests:2.0.0-SNAPSHOT, com.yahoo.elide:elide-integration-tests:jar:tests:2.0.0-SNAPSHOT: Could not find artifact com.yahoo.elide:elide-datastore-hibernate:jar:tests:2.0.0-SNAPSHOT
        at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:211)
        at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:195)
        ... 23 more
Caused by: org.eclipse.aether.resolution.DependencyResolutionException: The following artifacts could not be resolved: com.yahoo.elide:elide-datastore-hibernate:jar:tests:2.0.0-SNAPSHOT, com.yahoo.elide:elide-integration-tests:jar:tests:2.0.0-SNAPSHOT: Could not find artifact com.yahoo.elide:elide-datastore-hibernate:jar:tests:2.0.0-SNAPSHOT
        at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:384)
        at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:205)
        ... 24 more
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: The following artifacts could not be resolved: com.yahoo.elide:elide-datastore-hibernate:jar:tests:2.0.0-SNAPSHOT, com.yahoo.elide:elide-integration-tests:jar:tests:2.0.0-SNAPSHOT: Could not find artifact com.yahoo.elide:elide-datastore-hibernate:jar:tests:2.0.0-SNAPSHOT
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:444)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:246)
        at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:367)
        ... 25 more
Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact com.yahoo.elide:elide-datastore-hibernate:jar:tests:2.0.0-SNAPSHOT
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:434)
        ... 27 more
```

**Comment by kiangtengl** [comment]
Ignore the above as it seems that the tests are a dependency of the module, meaning that they need to be compiled.
