### ISSUE TITLE
Aggregation DataStore - cannot filter by enum type column

### ISSUE THREAD

**Issue by thaingo** [yahoo/elide#2407]
## Current Behavior
Not able to filter by enum type column

## Steps to Reproduce (for bugs)

1. Create 2 company instances
### company 1
```
curl --request POST 'http://localhost:8080/api/v1/company' \
--header 'Accept: application/vnd.api+json' \
--header 'Content-Type: application/vnd.api+json' \
--data-raw '{
    "data": {
        "type": "company",
        "id": "xyz",
        "attributes": {
            "type": "PRIVATE"
        }
    }
}'
```
### company 2
```
curl --request POST 'http://localhost:8080/api/v1/company' \
--header 'Accept: application/vnd.api+json' \
--header 'Content-Type: application/vnd.api+json' \
--data-raw '{
    "data": {
        "type": "company",
        "id": "abc",
        "attributes": {
            "type": "PUBLIC"
        }
    }
}'
```
2. Get company via JPA store using filter
it works perfectly.
```
curl --request GET 'http://localhost:8080/api/v1/company?filter[company]=type=in=PRIVATE' \
--header 'Accept: application/vnd.api+json' \
--header 'Content-Type: application/vnd.api+json'
```

3. Get company via aggregation store
### with filter `ini`
An empty array is returned
```
curl --request GET 'http://localhost:8080/api/v1/report?filter[report]=type=ini=PRIVATE' \
--header 'Accept: application/vnd.api+json' \
--header 'Content-Type: application/vnd.api+json' \
--header 'bypasscache: true'
```

### with filter `in`
An exception occurs
```
Caused by: org.h2.jdbc.JdbcSQLException: Hexadecimal string with odd number of characters: "0"; SQL statement:
SELECT DISTINCT `report`.`id` AS `companyId`,`report`.`type` AS `type` FROM `company` AS `report`  WHERE `report`.`type` IN (?)    LIMIT 500 OFFSET 0 [90003-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.util.StringUtils.convertHexToBytes(StringUtils.java:913)
	at org.h2.value.Value.convertTo(Value.java:1078)
	at org.h2.value.Value.convertTo(Value.java:617)
	at org.h2.value.Value.convertTo(Value.java:592)
	at org.h2.expression.Comparison.getValue(Comparison.java:271)
	at org.h2.expression.Expression.getBooleanValue(Expression.java:178)
	at org.h2.command.dml.Select.isConditionMet(Select.java:312)
	at org.h2.command.dml.Select$LazyResultQueryFlat.fetchNextRow(Select.java:1455)
	at org.h2.result.LazyResult.hasNext(LazyResult.java:79)
	at org.h2.result.LazyResult.next(LazyResult.java:59)
	at org.h2.command.dml.Select.queryFlat(Select.java:527)
	at org.h2.command.dml.Select.queryWithoutCache(Select.java:633)
	at org.h2.command.dml.Query.queryWithoutCacheLazyCheck(Query.java:114)
	at org.h2.command.dml.Query.query(Query.java:371)
	at org.h2.command.dml.Query.query(Query.java:333)
	at org.h2.command.CommandContainer.query(CommandContainer.java:114)
	at org.h2.command.Command.executeQuery(Command.java:202)
	at org.h2.jdbc.JdbcPreparedStatement.executeQuery(JdbcPreparedStatement.java:114)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
	at com.yahoo.elide.datastores.aggregation.queryengines.sql.NamedParamPreparedStatement.executeQuery(NamedParamPreparedStatement.java:47)
	at com.yahoo.elide.datastores.aggregation.queryengines.sql.SQLQueryEngine.lambda$runQuery$5(SQLQueryEngine.java:331)
```

## Your Environment

* Elide version used: 6.0.1
* Environment name and version (Java 1.8.0_152):JDK 15
* Operating System and version: MacOS
* Link to your project: [demo project](https://github.com/thaingo/elide-spring-boot-example/tree/verify-how-aggregation-store-supports-column-of-enum-type)

**Comment by aklish** [comment]
This might be related to a bug in H2 JDBC:
https://github.com/h2database/h2database/issues/633

We could provide a conversion method in the dialect so it can be avoided.

**Comment by aklish** [comment]
Spent some time debugging this.   When Elide sets a parameter (setObject) on prepared statement.  The JDBC driver doesn't know how an enum is stored (as text or by ordinal), so it tries to serialize it as an object (like to bytes).  

JPA has the benefit of `@Enumerated` to give a hint how the enum is stored. 

If a Java class is referencing the enum, Elide could look for something similar.   I have to give this some more thought about what would be ideal here if the enum is from HJSON directly.   Thoughts on how this ought to work from a configuration perspective?

**Comment by thaingo** [comment]
Making low-code tool is not that easy :).

I am thinking of an argument for column property `type`. It will looks:

Either
```
type : com.yahoo.elide.sample.models.SomeEnumType
resolver:
           {
                  type :  STRING
                  
            }
```

Or

```
type : com.yahoo.elide.sample.models.SomeEnumType
resolver:
           {
                  type :  INTEGER
                  
            }
```

What do you think?

**Comment by aklish** [comment]
A couple of thoughts:

- If the database stores as TEXT or VARCHAR and the column type is TEXT, I believe everything should work (filters, sorting, etc).
- The problem only exists when the database stores the enum ordinal.  
- We could look at `@Enumerated` for Java fields
- Ideally, it would be nice if we didn't have to add more configuration here.
- In theory, if the column has a list of values ([blue, red, gold, ...]), Elide could convert an ordinal in the database to text by its position in the list of values.  This would eliminate the need for having types that are also Java classes perhaps.

**Comment by aklish** [comment]
On second thought, we'll still need some extra configuration information to type coerce filters to the data type stored in the database.  For HJSON, maybe we can add two new types: ENUM_TEXT, and ENUM_ORDINAL (replacing the java type).

**Comment by thaingo** [comment]
> On second thought, we'll still need some extra configuration information to type coerce filters to the data type stored in the database. For HJSON, maybe we can add two new types: ENUM_TEXT, and ENUM_ORDINAL (replacing the java type).

This makes more sense in my view. We are also able to reuse the current implementation for the TEXT type as well.
