### ISSUE TITLE
Aggregation store - Could not instantiate specified check

### ISSUE THREAD

**Issue by thaingo** [yahoo/elide#2438]
In release 6.0.3, `user check` does not seem to work correctly but in previous releases including 6.0.2 and 6.0.1, the same `user check` works perfectly.

### I have the following setup
- An independent authentication service using Spring Security that returns a token with a role for a successful authentication
- A business service based on Elide 6.0.3, creating analytic models through hjson.
- `User check` in the business service looks like this:

```
@SecurityCheck(value = "admin")
public class IsAdmin extends UserCheck {

    @Override
    public boolean ok(User user) {
        return user.isInRole("ADMIN");
    }

}
```

### When I start the business service, an exception with below stack trace is thrown

```
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.yahoo.elide.Elide]: Factory method 'initializeElide' threw exception; nested exception is java.lang.IllegalArgumentException: Could not instantiate specified check 'admin'.
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653)
	... 33 common frames omitted
Caused by: java.lang.IllegalArgumentException: Could not instantiate specified check 'admin'.
	at com.yahoo.elide.core.dictionary.EntityDictionary.lambda$getCheck$5(EntityDictionary.java:381)
	at java.base/java.util.Map.computeIfAbsent(Map.java:1002)
	at com.google.common.collect.Synchronized$SynchronizedMap.computeIfAbsent(Synchronized.java:1185)
	at com.yahoo.elide.core.dictionary.EntityDictionary.getCheck(EntityDictionary.java:377)
	at com.yahoo.elide.datastores.aggregation.AggregationDataStore.lambda$validateExpression$11(AggregationDataStore.java:184)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1694)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at com.yahoo.elide.datastores.aggregation.AggregationDataStore.validateExpression(AggregationDataStore.java:183)
	at com.yahoo.elide.datastores.aggregation.AggregationDataStore.validateModelExpressionChecks(AggregationDataStore.java:151)
	at com.yahoo.elide.datastores.aggregation.AggregationDataStore.lambda$populateEntityDictionary$3(AggregationDataStore.java:93)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1694)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at com.yahoo.elide.datastores.aggregation.AggregationDataStore.populateEntityDictionary(AggregationDataStore.java:91)
	at com.yahoo.elide.datastores.multiplex.MultiplexManager.populateEntityDictionary(MultiplexManager.java:68)
	at com.yahoo.elide.core.datastore.inmemory.InMemoryDataStore.populateEntityDictionary(InMemoryDataStore.java:27)
	at com.yahoo.elide.Elide.doScans(Elide.java:121)
	at com.yahoo.elide.spring.config.ElideAutoConfiguration.initializeElide(ElideAutoConfiguration.java:191)
	at com.yahoo.elide.spring.config.ElideAutoConfiguration$$EnhancerBySpringCGLIB$$e63f001a.CGLIB$initializeElide$6(<generated>)
	at com.yahoo.elide.spring.config.ElideAutoConfiguration$$EnhancerBySpringCGLIB$$e63f001a$$FastClassBySpringCGLIB$$5e6fdcf8.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331)
	at com.yahoo.elide.spring.config.ElideAutoConfiguration$$EnhancerBySpringCGLIB$$e63f001a.initializeElide(<generated>)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
	... 34 common frames omitted
Caused by: java.lang.ClassNotFoundException: admin
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:606)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:168)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:377)
	at com.yahoo.elide.core.dictionary.EntityDictionary.lambda$getCheck$5(EntityDictionary.java:379)
	... 74 common frames omitted

```

## Your Environment

* Elide version used: 6.0.3
* Spring boot version used: 2.6.1
* Environment name and version (Java 1.8.0_152): 15
* Operating System and version: MacOS
* Link to your project: N/A

**Comment by aklish** [comment]
This line:
"Caused by: java.lang.ClassNotFoundException: admin"
makes it sounds like there is an issue scanning for the SecurityCheck.

**Comment by aklish** [comment]
There was a change in the ClassGraph version:

https://github.com/yahoo/elide/commit/a4a796bc72a7b60f145828bee9a3cabc6b9926c1

Can you try downgrading class graph to 4.8.132?

**Comment by aklish** [comment]
There are [tests](https://github.com/yahoo/elide/blob/master/elide-spring/elide-spring-boot-autoconfigure/src/test/java/example/tests/ControllerTest.java#L206-L226) for this in Elide but those don't seem to fail.  I suspect there is some package version issue going on - either in your environment or Elide itself.

**Comment by thaingo** [comment]
> There was a change in the ClassGraph version:
> 
> [a4a796b](https://github.com/yahoo/elide/commit/a4a796bc72a7b60f145828bee9a3cabc6b9926c1)
> 
> Can you try downgrading class graph to 4.8.132?

Unfortunately, downgrading does not fix the issue.

**Comment by thaingo** [comment]
> There are [tests](https://github.com/yahoo/elide/blob/master/elide-spring/elide-spring-boot-autoconfigure/src/test/java/example/tests/ControllerTest.java#L206-L226) for this in Elide but those don't seem to fail. I suspect there is some package version issue going on - either in your environment or Elide itself.

Could you advice further on what needs to be checked from my end?

**Comment by thaingo** [comment]
Added the check manually to dictionary, then face another exception with below stack trace:

```
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.yahoo.elide.modelconfig.DynamicConfiguration]: Factory method 'buildDynamicConfiguration' threw exception; nested exception is java.lang.IllegalStateException: Found undefined security checks: [admin]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653)
	... 33 common frames omitted
Caused by: java.lang.IllegalStateException: Found undefined security checks: [admin]
	at com.yahoo.elide.modelconfig.validator.DynamicConfigValidator.validateChecks(DynamicConfigValidator.java:645)
	at com.yahoo.elide.modelconfig.validator.DynamicConfigValidator.validateTableConfig(DynamicConfigValidator.java:592)
	at com.yahoo.elide.modelconfig.validator.DynamicConfigValidator.validateConfigs(DynamicConfigValidator.java:216)
	at com.yahoo.elide.modelconfig.validator.DynamicConfigValidator.validate(DynamicConfigValidator.java:177)
	at com.yahoo.elide.modelconfig.validator.DynamicConfigValidator.readAndValidateConfigs(DynamicConfigValidator.java:190)
	at com.yahoo.elide.spring.config.ElideAutoConfiguration.buildDynamicConfiguration(ElideAutoConfiguration.java:111)
	at com.yahoo.elide.spring.config.ElideAutoConfiguration$$EnhancerBySpringCGLIB$$c13a642d.CGLIB$buildDynamicConfiguration$2(<generated>)
	at com.yahoo.elide.spring.config.ElideAutoConfiguration$$EnhancerBySpringCGLIB$$c13a642d$$FastClassBySpringCGLIB$$85eaaed0.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331)
	at com.yahoo.elide.spring.config.ElideAutoConfiguration$$EnhancerBySpringCGLIB$$c13a642d.buildDynamicConfiguration(<generated>)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
	... 34 common frames omitted
```

I looked into the `DynamicValidator` and this exception is quite strange to me as the check is not a generated one and the check is not extend [RoleMemberCheck.](https://github.com/yahoo/elide/blob/master/elide-core/src/main/java/com/yahoo/elide/core/security/checks/prefab/Role.java#L38-L48) either.

**Comment by aklish** [comment]
Maybe the check doesn’t have equals and hash code defined and it is getting
lost in the map?

Aaron

**Comment by aklish** [comment]
> > There are [tests](https://github.com/yahoo/elide/blob/master/elide-spring/elide-spring-boot-autoconfigure/src/test/java/example/tests/ControllerTest.java#L206-L226) for this in Elide but those don't seem to fail. I suspect there is some package version issue going on - either in your environment or Elide itself.
> 
> Could you advice further on what needs to be checked from my end?

Here is what I would look at next (for the first exception):

1. Double check your dependencies and make sure that classgraph isn't being pulled in twice.  The first error suggests the class is not being scanned (but that doesn't explain the 2nd error).  
2. Can you reproduce this with the example project?  If so, that provides a basis to debug since I can't reproduce currently.
3. For debugging, I would probably start and see what happens immediately after class scanning.  I would be looking at the following locations:
  - For dynamic configuration validation: https://github.com/yahoo/elide/blob/master/elide-model-config/src/main/java/com/yahoo/elide/modelconfig/validator/DynamicConfigValidator.java#L107-L118
  - For static models: https://github.com/yahoo/elide/blob/master/elide-model-config/src/main/java/com/yahoo/elide/modelconfig/validator/DynamicConfigValidator.java#L107-L118

Your check should be found and added.   It is either being found (but somehow lost), or not found in the first place.  I'll take a look and see if I can reproduce the 2nd exception.

**Comment by aklish** [comment]
> Added the check manually to dictionary, then face another exception with below stack trace:
> 
> ```
> Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.yahoo.elide.modelconfig.DynamicConfiguration]: Factory method 'buildDynamicConfiguration' threw exception; nested exception is java.lang.IllegalStateException: Found undefined security checks: [admin]
> 	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
> 	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653)
> 	... 33 common frames omitted
> Caused by: java.lang.IllegalStateException: Found undefined security checks: [admin]
> 	at com.yahoo.elide.modelconfig.validator.DynamicConfigValidator.validateChecks(DynamicConfigValidator.java:645)
> 	at com.yahoo.elide.modelconfig.validator.DynamicConfigValidator.validateTableConfig(DynamicConfigValidator.java:592)
> 	at com.yahoo.elide.modelconfig.validator.DynamicConfigValidator.validateConfigs(DynamicConfigValidator.java:216)
> 	at com.yahoo.elide.modelconfig.validator.DynamicConfigValidator.validate(DynamicConfigValidator.java:177)
> 	at com.yahoo.elide.modelconfig.validator.DynamicConfigValidator.readAndValidateConfigs(DynamicConfigValidator.java:190)
> 	at com.yahoo.elide.spring.config.ElideAutoConfiguration.buildDynamicConfiguration(ElideAutoConfiguration.java:111)
> 	at com.yahoo.elide.spring.config.ElideAutoConfiguration$$EnhancerBySpringCGLIB$$c13a642d.CGLIB$buildDynamicConfiguration$2(<generated>)
> 	at com.yahoo.elide.spring.config.ElideAutoConfiguration$$EnhancerBySpringCGLIB$$c13a642d$$FastClassBySpringCGLIB$$85eaaed0.invoke(<generated>)
> 	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)
> 	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331)
> 	at com.yahoo.elide.spring.config.ElideAutoConfiguration$$EnhancerBySpringCGLIB$$c13a642d.buildDynamicConfiguration(<generated>)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
> 	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
> 	... 34 common frames omitted
> ```
> 
> I looked into the `DynamicValidator` and this exception is quite strange to me as the check is not a generated one (and does not extend [RoleMemberCheck.](https://github.com/yahoo/elide/blob/master/elide-core/src/main/java/com/yahoo/elide/core/security/checks/prefab/Role.java#L38-L48) either)

You can reference both your dynamic role based checks and static class checks in HJSON configuration.  The validator checks both when ensuring that all security checks are present.

**Comment by aklish** [comment]
I was able reproduce first issue.  Will share findings once I have them.
