### ISSUE TITLE
Elide dies on startup when GraphQL does not like enum string representation in model

### ISSUE THREAD

**Issue by markpatton** [yahoo/elide#2761]
If the model includes an enum which defines toString on a value and that string does not match what GraphQL expects, Elide startup will fail. In the spring boot example, this will happen even when GraphQL support is turned off.

## Expected Behavior

Elide should be able to handle any sort of enum string representation without failure.

Here is an example that will trigger the problem:

```java
@Include
@Entity
public class Widget {
    @Id
    private String name;

    private WidgetType type;
}

public enum WidgetType {
    GOOD("good-one"), BAD("bad-one");

    private String value;

    WidgetType(String value) {
        this.value = value;
    }

    @Override
    public String toString() {
        return value;
    }
}
```

## Current Behavior

I forked and updated elide-spring-boot-example to show the problem. Take a look at https://github.com/markpatton/elide-spring-boot-example.

Here is the exception which will be thrown on startup:
```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'scopedTarget.getQueryRunners' defined in class path resource [com/yahoo/elide/spring/config/ElideAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.yahoo.elide.graphql.QueryRunners]: Factory method 'getQueryRunners' threw exception; nested exception is graphql.AssertException: Name must be non-null, non-empty and match [_A-Za-z][_0-9A-Za-z]* - was 'good-one'
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:658)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:638)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1352)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1195)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$1(AbstractBeanFactory.java:374)
	at org.springframework.cloud.context.scope.GenericScope$BeanLifecycleWrapper.getBean(GenericScope.java:376)
	at org.springframework.cloud.context.scope.GenericScope.get(GenericScope.java:179)
```

## Possible Solution

I don't know enough about GraphQL to guess.

## Steps to Reproduce (for bugs)

1. git clone https://github.com/markpatton/elide-spring-boot-example
2. mvn package

## Context

The model I am using has many enums with string values that include a "-". I want to use it with JSON API, but even if GraphQL is turned off, Elide will fail to start when using spring boot. (Elide standalone will work with GraphQL turned off, but I'd like to use spring boot so I can integrate other components.)

## Your Environment
* Elide version used: 6.1.4
* Environment name and version (Java 1.8.0_152):  Java 11.0.16
* Operating System and version: Fedora 36
* Link to your project: https://github.com/markpatton/elide-spring-boot-example

**Comment by markpatton** [comment]
I tested against #2766 and it fixed the problem.

**Comment by aklish** [comment]
> I tested against #2766 and it fixed the problem.

👍
