### ISSUE TITLE
The elide-core/elide-spring-boot-starter 7.0.0-pr2 doesn't work with spring-boot 3.0.4

### ISSUE THREAD

**Issue by tzhao** [yahoo/elide#2918]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Elide version used:
* Environment name and version (Java 1.8.0_152):
* Operating System and version:
* Link to your project:

**Comment by aklish** [comment]
Spring 3.X only works with Elide 7 onwards.

**Comment by tzhao** [comment]
I tried Elide 7, but it still doesn't work. Is there any newer elide-spring-boot-starter which compatible with 3.x?

**Comment by tzhao** [comment]
11-03-2023 11:57:05.857 [restartedMain] ERROR SpringApplication.reportFailure - Application run failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.yahoo.elide.spring.controllers.JsonApiController' defined in BeanDefinition defined in null: Unexpected AOP exception
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:606)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:521)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:955)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:917)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:584)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:732)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:434)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:310)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1304)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1293)
	at gov.nih.gov.ncats.ifx.pounce.PounceApiApplication.main(PounceApiApplication.java:12)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49)
Caused by: org.springframework.aop.framework.AopConfigException: Unexpected AOP exception
	at org.springframework.aop.framework.CglibAopProxy.buildProxy(CglibAopProxy.java:222)
	at org.springframework.aop.framework.CglibAopProxy.getProxy(CglibAopProxy.java:158)
	at org.springframework.aop.framework.ProxyFactory.getProxy(ProxyFactory.java:110)
	at org.springframework.aop.scope.ScopedProxyFactoryBean.setBeanFactory(ScopedProxyFactoryBean.java:115)
	at org.springframework.cloud.context.scope.GenericScope$LockedScopedProxyFactoryBean.setBeanFactory(GenericScope.java:448)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeAwareMethods(AbstractAutowireCapableBeanFactory.java:1783)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1750)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:599)
	... 20 common frames omitted
Caused by: java.lang.ClassCastException: class com.yahoo.elide.spring.controllers.JsonApiController$$SpringCGLIB$$0 cannot be cast to class org.springframework.cglib.proxy.Factory (com.yahoo.elide.spring.controllers.JsonApiController$$SpringCGLIB$$0 and org.springframework.cglib.proxy.Factory are in unnamed module of loader 'app')
	at org.springframework.aop.framework.ObjenesisCglibAopProxy.createProxyClassAndInstance(ObjenesisCglibAopProxy.java:91)
	at org.springframework.aop.framework.CglibAopProxy.buildProxy(CglibAopProxy.java:213)
	... 27 common frames omitted

**Comment by aklish** [comment]
You need to use the elide-7.x branch of spring boot starter

**Comment by tzhao** [comment]
I tried but got error:  Could not find artifact com.yahoo.elide:elide-spring-boot-starter:jar:**7.0.0-RC7-SNAPSHOT**
Any suggestions and pom.xml examples are highly appreciated!

**Comment by aklish** [comment]
Replace that version with the latest Elide 7 released version.

**Comment by tzhao** [comment]
We're unable to move forward until this problem is resolved, I really appreciate your help!

**Comment by aklish** [comment]
Sure but traveling so will be a week or so.

**Comment by justin-tay** [comment]
I didn't investigate this fully but this seems to be caused by Spring Boot Dev Tools and the fact that the controllers are annotated `@Configuration` which also creates a proxy by default. I don't think that the `@Configuration` annotations on the controllers are necessary and removing them seems to solve the issue.

If you need a quick fix removing Spring Boot Dev Tools also makes the problem go away.

**Comment by tzhao** [comment]
Thank you so much @justin-tay . After removing Spring Boot Dev Tools, I got another error: ```
required a bean of type 'com.yahoo.elide.graphql.QueryRunners' that could not be found.
Action:

Consider defining a bean of type 'com.yahoo.elide.graphql.QueryRunners' in your configuration.
```
We are eagerly awaiting your new release. I have developed a strong affinity for Elide, and would prefer not to part ways with it as we embark on our new project. Thank you again!

**Comment by justin-tay** [comment]
Are you using the code at https://github.com/yahoo/elide-spring-boot-example/tree/elide-7.x to test?

You should have that bean in `@RefreshScope` if `elide.graphql.enabled` is set to `true`.

**Comment by aklish** [comment]
So I tried 3.0.4 spring tonight with the elide-7.x branch of the elide-spring-boot-example repo.  I wasn't able to reproduce this problem. The project launched and everything seems to check out fine.   I bumped the elide-7.x branch to now use 3.0.4 spring.

I suspect there is something else going on with your pom that is different than the example project?

**Comment by justin-tay** [comment]
I think it would be helpful to understand what you are trying to do as that snippet looks a little different from the one from the auto configuration. The auto configuration will already take care of creating the `GraphqlController` so are you attempting to define your own? If you aren't using the example at https://github.com/yahoo/elide-spring-boot-example/tree/elide-7.x then a small reproducer project would be easier to understand.

The message just says you are missing a `com.yahoo.elide.graphql.QueryRunners` in the application context.

If you were using the `ElideAutoConfiguration` this should have been automatically created for you https://github.com/yahoo/elide/blob/97c7bb768be604fa72b8361a6f71462ab5912ea9/elide-spring/elide-spring-boot-autoconfigure/src/main/java/com/yahoo/elide/spring/config/ElideAutoConfiguration.java#L224-L233.

**Comment by tzhao** [comment]
Our GraphqlController intercepts GraphQL queries for logging. monitoring, security etc. We discovered that on the Dev environment, the configuration file had mistakenly set 'elide.graphql.enabled' to false. After correcting this, the issue was resolved. Thank you very much for your assistance! 
Go Elied!

**Comment by justin-tay** [comment]
Looking at the `@ConditionalOnExpression("!${elide.graphql.enabled}")` annotation on your custom `GraphqlController` setting `elide.graphql.enabled` to `true` enabled the default auto configuration `GraphqlController` but disabled your custom `GraphqlController`.

You might want to consider leaving it as `false` and just setting your own configuration for `QueryRunners`.

```java
@Configuration
public class GraphqlConfiguration {
     @Bean 
     @RefreshScope 
     public QueryRunners getQueryRunners(RefreshableElide refreshableElide) { 
         return new QueryRunners(refreshableElide); 
     } 
}
```

**Comment by tzhao** [comment]
Great idea! Thank you @justin-tay
