### ISSUE TITLE
"no transaction is in progress" with spring boot and 7.0.0 pr5

### ISSUE THREAD

**Issue by bladedancer** [yahoo/elide#3019]
I'm upgrading from elide 6 to 7 (due to internal changes requiring me to move to spring boot 3). It's using JPA backed by postgres.

With v7.0.0-pr3 everything is working as expected, however with v7.0.0-pr5 it get a "no transaction is in progress" error;

  2023-06-28 15:25:52 [MvcAsync1] ERROR c.y.e.d.j.t.AbstractJpaTransaction - Caught entity manager exception during flush
  jakarta.persistence.TransactionRequiredException: no transaction is in progress
	  at org.hibernate.internal.AbstractSharedSessionContract.checkTransactionNeededForUpdateOperation(AbstractSharedSessionContract.java:471)
	  at org.hibernate.internal.SessionImpl.checkTransactionNeededForUpdateOperation(SessionImpl.java:2499)
	  at org.hibernate.internal.SessionImpl.doFlush(SessionImpl.java:1403)
	  at org.hibernate.internal.SessionImpl.flush(SessionImpl.java:1398)
	  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	  at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	  at org.springframework.orm.jpa.ExtendedEntityManagerCreator$ExtendedEntityManagerInvocationHandler.invoke(ExtendedEntityManagerCreator.java:360)
	  at jdk.proxy2/jdk.proxy2.$Proxy219.flush(Unknown Source)
	  at com.yahoo.elide.datastores.jpa.SupplierEntityManager.flush(SupplierEntityManager.java:106)
	  at com.yahoo.elide.datastores.jpa.transaction.AbstractJpaTransaction.flush(AbstractJpaTransaction.java:94)
	  at com.yahoo.elide.core.datastore.inmemory.InMemoryStoreTransaction.flush(InMemoryStoreTransaction.java:191)
	  at com.yahoo.elide.Elide.handleRequest(Elide.java:607)
	  at com.yahoo.elide.Elide.get(Elide.java:263)
	  at com.yahoo.elide.spring.controllers.JsonApiController$1.call(JsonApiController.java:85)
	  at com.yahoo.elide.spring.controllers.JsonApiController$1.call(JsonApiController.java:82)
	  at org.springframework.web.context.request.async.WebAsyncManager.lambda$startCallableProcessing$4(WebAsyncManager.java:341)
	  at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	  at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264)
	  at java.base/java.util.concurrent.FutureTask.run(FutureTask.java)
	  at java.base/java.lang.Thread.run(Thread.java:833)

Presumably this is related to the changes in https://github.com/yahoo/elide/pull/2953 and I'm just missing a step but I couldn't find anything in the samples or docs that resolved it. Are there any examples running JPA/spring-boot with 7.0.0 PR5?

**Comment by bladedancer** [comment]
FYI - updated the elide-spring-boot-example to pr5.....it worked fine (at least with h2, will need to check postgres but I assume it will work too). So not sure why my situation differs from that sample - there's nothing obvious at a high level.

Unfortunately my code is not something I can share - but if anyone knows what could trigger this situation then that would be extremely helpful.

**Comment by bladedancer** [comment]
Ok - seems it was user error. Another part of the code was setting the transaction manager to be DataSourceTransactionManager.

This causes a problem because the hibernate flush mode stays AUTO on the flush of DataSourceTransactionManager, whereas JpaTransactionManager sets it to manual.
