### ISSUE TITLE
Attempting to deploy standalone Elide WAR app results in "java.lang.IllegalStateException: No Jetty ContextHandler, Jakarta WebSocket SCI unavailable"

### ISSUE THREAD

**Issue by QubitPi** [yahoo/elide#3045]
Hi Elide team, our people love Elide and are trying to spin up an Elide app in standalone mode by following this [guide](https://github.com/yahoo/elide/tree/master/elide-standalone); but we have trouble at runtime (we are using jersey on jetty)

Could we get some help on the following error and see if we are missing anything?

> In fact our app is at https://github.com/paion-data/astraios/tree/enable-elide (`enable-elide` branch)
> The way to re-product our error is by
> 
> 1. [Downloading Jetty 11.0.15](https://www.eclipse.org/jetty/download.php)
> 2. Extracting by `tar -xzvf jetty-home-11.0.15.tar.gz`
> 3. `export JETTY_HOME=/path/to/jetty-home-11.0.15`
> 4. `mkdir -p /path/to/jetty-base`
> 5. `cd /path/to/jetty-base`
> 6. `java -jar $JETTY_HOME/start.jar --add-module=annotations,server,http,deploy`
> 7. Package our app at https://github.com/paion-data/astraios/tree/enable-elide via `mvn clean package -Dcheckstyle.skip -DskipTests` to generate `target/*.war` file
> 8. copy over `target/*.war` file into `/path/to/jetty-base/webapps` and rename it to `ROOT.war`
> 9. start Elide app with `java -jar $JETTY_HOME/start.jar` and people will see error like the following:

```
java.lang.IllegalStateException: No Jetty ContextHandler, Jakarta WebSocket SCI unavailable
	at org.eclipse.jetty.servlet.ServletContextHandler.getServletContextHandler(ServletContextHandler.java:103)
	at org.eclipse.jetty.websocket.jakarta.server.config.JakartaWebSocketServletContainerInitializer.onStartup(JakartaWebSocketServletContainerInitializer.java:165)
	at org.eclipse.jetty.servlet.ServletContainerInitializerHolder.doStart(ServletContainerInitializerHolder.java:148)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:171)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	at org.eclipse.jetty.servlet.ServletContextHandler$ServletContainerInitializerStarter.doStart(ServletContextHandler.java:1660)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:369)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1305)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:902)
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:306)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:533)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
	at org.eclipse.jetty.deploy.bindings.StandardStarter.processBinding(StandardStarter.java:40)
	at org.eclipse.jetty.deploy.AppLifeCycle.runBindings(AppLifeCycle.java:183)
	at org.eclipse.jetty.deploy.DeploymentManager.requestAppGoal(DeploymentManager.java:516)
	at org.eclipse.jetty.deploy.DeploymentManager.addApp(DeploymentManager.java:151)
	at org.eclipse.jetty.deploy.providers.ScanningAppProvider.fileAdded(ScanningAppProvider.java:186)
	at org.eclipse.jetty.deploy.providers.WebAppProvider.fileAdded(WebAppProvider.java:456)
	at org.eclipse.jetty.deploy.providers.ScanningAppProvider$1.fileAdded(ScanningAppProvider.java:58)
	at org.eclipse.jetty.util.Scanner$DiscreteListener.pathAdded(Scanner.java:282)
	at org.eclipse.jetty.util.Scanner.reportAddition(Scanner.java:836)
	at org.eclipse.jetty.util.Scanner.reportDifferences(Scanner.java:802)
	at org.eclipse.jetty.util.Scanner.scan(Scanner.java:709)
	at org.eclipse.jetty.util.Scanner.doStart(Scanner.java:597)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:171)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:121)
	at org.eclipse.jetty.deploy.providers.ScanningAppProvider.doStart(ScanningAppProvider.java:158)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
	at org.eclipse.jetty.deploy.DeploymentManager.startAppProvider(DeploymentManager.java:605)
	at org.eclipse.jetty.deploy.DeploymentManager.doStart(DeploymentManager.java:246)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:171)
	at org.eclipse.jetty.server.Server.start(Server.java:470)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:121)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:89)
	at org.eclipse.jetty.server.Server.doStart(Server.java:415)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
	at org.eclipse.jetty.xml.XmlConfiguration.main(XmlConfiguration.java:1875)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.jetty.start.Main.invokeMain(Main.java:229)
	at org.eclipse.jetty.start.Main.start(Main.java:528)
	at org.eclipse.jetty.start.Main.main(Main.java:76)
```

For reference, here is how we configure Elide on `enable-elide` branch:

```java
import com.yahoo.elide.Elide;
import com.yahoo.elide.ElideSettings;
import com.yahoo.elide.annotation.Include;
import com.yahoo.elide.core.TransactionRegistry;
import com.yahoo.elide.core.datastore.DataStore;
import com.yahoo.elide.core.dictionary.EntityDictionary;
import com.yahoo.elide.modelconfig.DynamicConfiguration;
import com.yahoo.elide.standalone.Util;
import com.yahoo.elide.standalone.config.ElideStandaloneSettings;

import org.glassfish.hk2.api.ServiceLocator;
import org.glassfish.jersey.internal.inject.AbstractBinder;

import jakarta.inject.Inject;
import jakarta.persistence.Entity;
import jakarta.persistence.EntityManagerFactory;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.servlet.ServletContext;
import jakarta.ws.rs.ApplicationPath;
import jakarta.ws.rs.core.Context;
import net.jcip.annotations.Immutable;
import net.jcip.annotations.ThreadSafe;

import java.io.IOException;
import java.util.Optional;
import java.util.Properties;

/**
 * The resource configuration for the web applications.
 */
@Immutable
@ThreadSafe
@ApplicationPath("v1")
public class ResourceConfig extends org.glassfish.jersey.server.ResourceConfig {

    private final ServiceLocator injector;

    @Entity
    @Table(name="ArtifactGroup")
    @Include(rootLevel = true, name = "group", friendlyName = "group", description = "group desc")
    public class ArtifactGroup {
        @Id
        public String name = "";

        public String description = "";
    }

    public class AstraiosBinder extends AbstractBinder {

        @Override
        protected void configure() {
            ElideStandaloneSettings settings = new ElideStandaloneSettings() {
                @Override
                public String getModelPackageName() {
                    return ArtifactGroup.class.getPackage().getName();
                }

                @Override
                public Properties getDatabaseProperties() {
                    Properties options = new Properties();

                    options.put("hibernate.dialect", "org.hibernate.dialect.MySQL5Dialect");
                    options.put("javax.persistence.jdbc.driver", "com.mysql.jdbc.Driver");
                    options.put("javax.persistence.jdbc.url", "jdbc:mysql://localhost:3306/testDB");
                    options.put("javax.persistence.jdbc.user", "root");
                    options.put("javax.persistence.jdbc.password", "root");

                    return options;
                }
            };

            EntityManagerFactory entityManagerFactory = Util.getEntityManagerFactory(
                    settings.getClassScanner(),
                    settings.getModelPackageName(),
                    false,
                    settings.getDatabaseProperties()
            );
            DataStore dataStore = settings.getDataStore(entityManagerFactory);

            Optional<DynamicConfiguration> dynamicConfiguration;
            try {
                dynamicConfiguration = settings.getDynamicConfiguration(settings.getClassScanner());
            } catch (IOException exception) {
                throw new IllegalStateException(exception);
            }
            EntityDictionary entityDictionary = settings.getEntityDictionary(
                    injector,
                    settings.getClassScanner(),
                    dynamicConfiguration,
                    settings.getEntitiesToExclude()
            );

            ElideSettings elideSettings = settings.getElideSettings(entityDictionary, dataStore, settings.getObjectMapper());
            Elide elide = new Elide(
                    elideSettings,
                    new TransactionRegistry(),
                    elideSettings.getDictionary().getScanner(),
                    false
            );

            // All Elide bindings
            bind(elide).to(Elide.class).named("elide");
            bind(elideSettings).to(ElideSettings.class);
            bind(elideSettings.getDictionary()).to(EntityDictionary.class);
            bind(elideSettings.getDataStore()).to(DataStore.class).named("elideDataStore");
        }
    }

    @Inject
    public ResourceConfig(ServiceLocator injector, @Context ServletContext servletContext) {
        this.injector = injector;
        register(new AstraiosBinder());
    }
}

```

Thanks for your time! :)

**Comment by justin-tay** [comment]
From what I can tell the `elide-standalone` library and guide covers running Elide on embedded Jetty only and not as a WAR deployed on Jetty. A lot of the configuration that the library does doesn't translate when built as a WAR. The example application for 7.x is at https://github.com/yahoo/elide-standalone-example/tree/elide-7.x.

That said this specific error is because you need the `websocket-jakarta` module.

`java -jar $JETTY_HOME/start.jar --add-module=annotations,server,http,deploy,websocket-jakarta`

After which it should still fail because `com.yahoo.elide.graphql.subscriptions.websocket.SubscriptionWebSocket` doesn't have a  public no-arg constructor.

Even after adding the constructor, the startup still fails because
- There is no MySQL database driver in the POM `mysql-connector-j`
- There is no `org.hibernate.dialect.MySQL5Dialect` in Hibernate 6

After that you would have to register the necessary resources that would have been registered by `com.yahoo.elide.standalone.ElideStandalone` in embedded Jetty. Note also that the WAR will contain a lot of Jetty libraries as it has been set to `compile` so you'll want to set those as `provided` if you want a WAR.

If you really need a WAR it's probably easier to configure Elide using Spring Boot with WAR packaging.

**Comment by QubitPi** [comment]
Thank you very much for the guidance, @justin-tay ! The `websocket-jakarta` module really helped. I have added the `mysql-connector-j` you mentioned and changed `MySQL5Dialect` to `MySQLDialect`.

I also re-studied the Elide resource binding and finally our WAR is running properly!

Thanks again for helping us!
