### ISSUE TITLE
In Filter causes 500 error for Set

### ISSUE THREAD

**Issue by white3km** [yahoo/elide#3268]
Hello, previously with Elide 6.1.12 the setup described below worked for the JPQL IN filter. After migrating to Elide 7.1.0, I'm receiving a 500 error for type mismatch.

## Expected Behavior
I have an entity with a field that is a comma delimited list that we are treating as a Set by using a converter. The actual database column type is text. Previously we could filter on this field with an IN operator that utilized a custom JPQL filter fragment and would return the expected results.

### Unit test
```
@Test
  void whenApiGetAlphaByFilter() {
    given()
            .headers(populateUserHeader(TEST_USERNAME))
            .get(apiPath + "/" + TABLE_ALPHA+ "?filter=(cdlList=in=('orange'))")
            .then()
            .log()
            .all()
            .assertThat()
            .statusCode(HttpStatus.SC_OK)
            .body("data", hasSize(4));
  }
```

### Database Definition
```
CREATE TABLE alpha (
    id uuid NOT NULL,
    cdl_value text DEFAULT ''::text NOT NULL
);
```
### Entity
```
@Entity
@Table(name = TABLE_ALPHA, schema = DB_SCHEMA)
@Include(name = TABLE_ALPHA)
public class Alpha {
    @JPQLFilterFragment(operator = Operator.IN_INSENSITIVE, generator = StringListInFilter.class)
    @Convert(converter = CommaDelimitedConverter.class)
    @NotNull
    @Column(name = "cdl_value", nullable = false)
    public Set<String> getCdlList() {
      return cdlList;
    }
}
```
### Elide Config
```
@Bean
  JsonApiSettingsBuilderCustomizer getJsonApiSettingsBuilder(EntityDictionary entityDictionary) {
    return builder ->
        builder
            .updateStatus200()
            .joinFilterDialect(
                new RSQLFilterDialect(
                    entityDictionary, new CaseSensitivityStrategy.FIQLCompliant(), Boolean.TRUE))
            .subqueryFilterDialect(
                new RSQLFilterDialect(
                    entityDictionary, new CaseSensitivityStrategy.FIQLCompliant(), Boolean.TRUE));
  }
```

### Converter
```
public class CommaDelimitedConverter implements AttributeConverter<Set<String>, String> {
  @Override
  public String convertToDatabaseColumn(Set<String> values) {
    String result = "";
    if (values != null && !values.isEmpty()) {
      result = String.join(",", values);
    }
    return result;
  }

  @Override
  public Set<String> convertToEntityAttribute(String value) {
    Set<String> result = new HashSet<>();
    if (value != null && !value.isBlank()) {
      Collections.addAll(result, value.split(","));
    }
    return result;
  }
}
```
### JPQL Fragment
```
public class StringListInFilter implements JPQLPredicateGenerator {
  private static final String FILTER_PATH_NOT_NULL = "Filtering field path cannot be empty.";
  private static final String FILTER_ALIAS_NOT_NULL = "Filtering alias cannot be empty.";
  private final Boolean caseInsensitive;

  public StringListInFilter() {
    this.caseInsensitive = Boolean.TRUE;
  }

  public StringListInFilter(Boolean caseInsensitive) {
    this.caseInsensitive = caseInsensitive;
  }

  @Override
  public String generate(FilterPredicate filterPredicate, Function<Path, String> aliasGenerator) {
    log.warn("IN FILTER FUNCTION");

    String columnAlias = aliasGenerator.apply(filterPredicate.getPath());
    List<FilterPredicate.FilterParameter> parameters = filterPredicate.getParameters();

    if (!StringUtils.hasText(columnAlias)) {
      log.error("columnAlias cannot be NULL or empty");
      throw new InvalidValueException(FILTER_PATH_NOT_NULL);
    }
    if (parameters.isEmpty() || !StringUtils.hasText(parameters.get(0).getName())) {
      log.error("One non-null, non-empty argument was expected");
      throw new InvalidValueException(FILTER_ALIAS_NOT_NULL);
    }

    StringBuilder sb = new StringBuilder();
    sb.append("(");
    Iterator<FilterPredicate.FilterParameter> filterIterator = parameters.listIterator();
    // Uses custom database function with ORs
    sb.append(")");
    return sb.toString();
  }
}
```

## Current Behavior
Currently I receive a 500 error with a type mismatch error in the logs.  After putting a log statement in the JPQLFilterFragment, I don't think it's reached before the error.
```
{
    "timestamp": "2024-07-30T15:01:09.031+00:00",
    "status": 500,
    "error": "Internal Server Error",
    "path": "/api/alpha"
}

```
```
org.hibernate.query.QueryArgumentException: Argument [orange] of type [java.lang.String] did not match parameter type [java.util.Set (n/a)]
	at org.hibernate.query.spi.QueryParameterBindingValidator.validate(QueryParameterBindingValidator.java:85) ~[hibernate-core-6.5.2.Final.jar:6.5.2.Final]
	at org.hibernate.query.spi.QueryParameterBindingValidator.validate(QueryParameterBindingValidator.java:32) ~[hibernate-core-6.5.2.Final.jar:6.5.2.Final]
	at org.hibernate.query.internal.QueryParameterBindingImpl.validate(QueryParameterBindingImpl.java:362) ~[hibernate-core-6.5.2.Final.jar:6.5.2.Final]
	at org.hibernate.query.internal.QueryParameterBindingImpl.setBindValue(QueryParameterBindingImpl.java:137) ~[hibernate-core-6.5.2.Final.jar:6.5.2.Final]
	at org.hibernate.query.spi.AbstractCommonQueryContract.setParameter(AbstractCommonQueryContract.java:842) ~[hibernate-core-6.5.2.Final.jar:6.5.2.Final]
	at org.hibernate.query.spi.AbstractSelectionQuery.setParameter(AbstractSelectionQuery.java:882) ~[hibernate-core-6.5.2.Final.jar:6.5.2.Final]
	at org.hibernate.query.sqm.internal.QuerySqmImpl.setParameter(QuerySqmImpl.java:1200) ~[hibernate-core-6.5.2.Final.jar:6.5.2.Final]
	at org.hibernate.query.sqm.internal.QuerySqmImpl.setParameter(QuerySqmImpl.java:136) ~[hibernate-core-6.5.2.Final.jar:6.5.2.Final]
	at com.yahoo.elide.datastores.jpa.porting.QueryWrapper.setParameter(QueryWrapper.java:42) ~[elide-datastore-jpa-7.1.0.jar:na]
	at com.yahoo.elide.datastores.jpql.query.AbstractHQLQueryBuilder.lambda$supplyFilterQueryParameters$0(AbstractHQLQueryBuilder.java:97) ~[elide-datastore-hibernate-7.1.0.jar:na]
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511) ~[na:na]
	at com.yahoo.elide.datastores.jpql.query.AbstractHQLQueryBuilder.supplyFilterQueryParameters(AbstractHQLQueryBuilder.java:96) ~[elide-datastore-hibernate-7.1.0.jar:na]
	at com.yahoo.elide.datastores.jpql.query.RootCollectionFetchQueryBuilder.build(RootCollectionFetchQueryBuilder.java:111) ~[elide-datastore-hibernate-7.1.0.jar:na]
	at com.yahoo.elide.datastores.jpql.JPQLTransaction.loadObjects(JPQLTransaction.java:127) ~[elide-datastore-hibernate-7.1.0.jar:na]
	at com.yahoo.elide.core.datastore.inmemory.InMemoryStoreTransaction.lambda$loadObjects$2(InMemoryStoreTransaction.java:117) ~[elide-core-7.1.0.jar:na]
	at com.yahoo.elide.core.datastore.inmemory.InMemoryStoreTransaction.fetchData(InMemoryStoreTransaction.java:262) ~[elide-core-7.1.0.jar:na]
	at com.yahoo.elide.core.datastore.inmemory.InMemoryStoreTransaction.loadObjects(InMemoryStoreTransaction.java:123) ~[elide-core-7.1.0.jar:na]
	at com.yahoo.elide.core.PersistentResource.loadRecords(PersistentResource.java:374) ~[elide-core-7.1.0.jar:na]
	at com.yahoo.elide.jsonapi.parser.state.CollectionTerminalState.getResourceCollection(CollectionTerminalState.java:146) ~[elide-core-7.1.0.jar:na]
	at com.yahoo.elide.jsonapi.parser.state.CollectionTerminalState.handleGet(CollectionTerminalState.java:76) ~[elide-core-7.1.0.jar:na]
	at com.yahoo.elide.jsonapi.parser.state.StateContext.handleGet(StateContext.java:108) ~[elide-core-7.1.0.jar:na]
	at com.yahoo.elide.jsonapi.parser.GetVisitor.visitQuery(GetVisitor.java:31) ~[elide-core-7.1.0.jar:na]
	at com.yahoo.elide.jsonapi.parser.GetVisitor.visitQuery(GetVisitor.java:18) ~[elide-core-7.1.0.jar:na]
	at com.yahoo.elide.generated.parsers.CoreParser$QueryContext.accept(CoreParser.java:582) ~[elide-core-7.1.0.jar:na]
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46) ~[antlr4-runtime-4.13.1.jar:4.13.1]
	at com.yahoo.elide.generated.parsers.CoreBaseVisitor.visitStart(CoreBaseVisitor.java:21) ~[elide-core-7.1.0.jar:na]
	at com.yahoo.elide.jsonapi.parser.BaseVisitor.visitStart(BaseVisitor.java:47) ~[elide-core-7.1.0.jar:na]
	at com.yahoo.elide.jsonapi.parser.BaseVisitor.visitStart(BaseVisitor.java:33) ~[elide-core-7.1.0.jar:na]
	at com.yahoo.elide.generated.parsers.CoreParser$StartContext.accept(CoreParser.java:118) ~[elide-core-7.1.0.jar:na]
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18) ~[antlr4-runtime-4.13.1.jar:4.13.1]
	at com.yahoo.elide.jsonapi.JsonApi.visit(JsonApi.java:251) ~[elide-core-7.1.0.jar:na]
	at com.yahoo.elide.jsonapi.JsonApi.lambda$get$0(JsonApi.java:112) ~[elide-core-7.1.0.jar:na]
	at com.yahoo.elide.jsonapi.JsonApi.handleRequest(JsonApi.java:276) ~[elide-core-7.1.0.jar:na]
	at com.yahoo.elide.jsonapi.JsonApi.get(JsonApi.java:104) ~[elide-core-7.1.0.jar:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
	at org.springframework.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:281) ~[spring-core-6.1.10.jar:6.1.10]
	at org.springframework.cloud.context.scope.GenericScope$LockedScopedProxyFactoryBean.invoke(GenericScope.java:482) ~[spring-cloud-context-4.1.3.jar:4.1.3]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184) ~[spring-aop-6.1.10.jar:6.1.10]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768) ~[spring-aop-6.1.10.jar:6.1.10]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:720) ~[spring-aop-6.1.10.jar:6.1.10]
	at com.yahoo.elide.jsonapi.JsonApi$$SpringCGLIB$$0.get(<generated>) ~[elide-core-7.1.0.jar:na]
	at com.yahoo.elide.spring.controllers.JsonApiController$1.call(JsonApiController.java:82) ~[elide-spring-boot-autoconfigure-7.1.0.jar:na]
	at com.yahoo.elide.spring.controllers.JsonApiController$1.call(JsonApiController.java:79) ~[elide-spring-boot-autoconfigure-7.1.0.jar:na]
	at org.springframework.web.context.request.async.WebAsyncManager.lambda$startCallableProcessing$4(WebAsyncManager.java:348) ~[spring-web-6.1.10.jar:6.1.10]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:840) ~[na:na]

```

## Your Environment

* Elide version used: Elide 7.1.0
* Environment name and version (Java 1.8.0_152): Java 17.0.11
* Operating System and version: Windows
* Link to your project:

**Comment by justin-tay** [comment]
You registered the fragment using `Operator.IN_INSENSITIVE` which is `=ini=`.

```java
@JPQLFilterFragment(operator = Operator.IN_INSENSITIVE, generator = StringListInFilter.class)
```

But your call is using `=in=`

`get(apiPath + "/" + TABLE_ALPHA+ "?filter=(cdlList=in=('orange'))")`

**Comment by white3km** [comment]
Looking back through my code history. I previously had JPQLFilterFragment as Operator.IN and then changed it to Operator.IN_INSENSITIVE during Elide 5.1.1. That setup has worked from 5.1.1 through 6.1.12 with the JPQLFilterFragment being used for the =in= path. My understanding was since I set the config with CaseSensitivityStrategy.FIQLCompliant(). It should treat the IN operator as IN_INSENSITIVE.

https://github.com/yahoo/elide/blob/fbbf2a860d79e7ca5794b16740a29f57c23d5c1f/elide-core/src/main/java/com/yahoo/elide/core/filter/dialect/CaseSensitivityStrategy.java#L31

https://github.com/yahoo/elide/blob/fbbf2a860d79e7ca5794b16740a29f57c23d5c1f/elide-core/src/test/java/com/yahoo/elide/core/filter/dialect/RSQLFilterDialectWithFIQLCompliantStrategyTest.java#L46

I think the real issue is that the Case Sensitivity Strategy is not being applied properly or I'm not configuring it right.  I've noticed that other filter fields are not case insensitive in Elide 7 (see below).

# Elide 6
## Elide Configuration

I set the CaseSensitivityStrategy.FIQLCompliant() in the RefreshableElide.

```
@Configuration
public class ElideConfig extends ElideAutoConfiguration {
 @Override
  public RefreshableElide getRefreshableElide(
      EntityDictionary dictionary,
      DataStore dataStore,
      HeaderUtils.HeaderProcessor headerProcessor,
      TransactionRegistry transactionRegistry,
      ElideConfigProperties settings,
      JsonApiMapper mapper,
      ErrorMapper errorMapper) {

    ElideSettingsBuilder builder =
        new ElideSettingsBuilder(dataStore)
            .withUpdate200Status()
            .withEntityDictionary(dictionary)
            .withErrorMapper(errorMapper)
            .withJsonApiMapper(mapper)
            .withDefaultMaxPageSize(settings.getMaxPageSize())
            .withDefaultPageSize(settings.getPageSize())
            .withJoinFilterDialect(
                new RSQLFilterDialect(
                    dictionary, new CaseSensitivityStrategy.FIQLCompliant(), Boolean.TRUE))
            .withSubqueryFilterDialect(
                new RSQLFilterDialect(
                    dictionary, new CaseSensitivityStrategy.FIQLCompliant(), Boolean.TRUE))
            .withAuditLogger(new Slf4jLogger())
            .withBaseUrl(settings.getBaseUrl())
            .withISO8601Dates(DATE_FORMAT_ISO, TimeZone.getTimeZone("UTC"))
            .withJsonApiPath(settings.getJsonApi().getPath())
            .withHeaderProcessor(headerProcessor);

    // Other code copied from Elide spring...

    Elide elide = new Elide(builder.build(), transactionRegistry, dictionary.getScanner(), true);

    return new RefreshableElide(elide);
  }
}

```

## User's given name = 'Justin'
### /user?filter=(givenName==%27*Justin*%27)

Record is successfully returned

```
// Log
c.y.e.d.jpql.query.DefaultQueryLogger    : Query Hash: 41637738	HQL Query: SELECT gov_disa_dso_tardys3_s3_api_user_entity_User FROM entity.User AS entity_User    WHERE (LOWER(user_entity_User.givenName) LIKE CONCAT('%', CONCAT(LOWER(:givenName_5a16e663_0), '%')) AND (1 = 1))  order by user_entity_User.updatedAt desc
c.yahoo.elide.core.utils.TimedFunction   : Query Hash: 41637738	Time spent: 3
c.y.e.d.jpql.query.DefaultQueryLogger    : Query Hash: 907360069	HQL Query: SELECT COUNT(DISTINCT user_entity_User)  FROM entity.User AS user_entity_User    WHERE (LOWER(user_entity_User.givenName) LIKE CONCAT('%', CONCAT(LOWER(:givenName_5a16e663_0), '%')) AND (1 = 1))
c.yahoo.elide.core.utils.TimedFunction   : Query Hash: 907360069	Time spent: 3
```
### /user?filter=(givenName==%27*JUSTIN*%27)

Record is successfully returned

```
// Log
c.y.e.d.jpql.query.DefaultQueryLogger    : Query Hash: 1712141559	HQL Query: SELECT user_entity_User FROM user.entity.User AS user_entity_User    WHERE (LOWER(user_entity_User.givenName) LIKE CONCAT('%', CONCAT(LOWER(:givenName_14ceb603_0), '%')) AND (1 = 1))  order by user_entity_User.updatedAt desc
c.yahoo.elide.core.utils.TimedFunction   : Query Hash: 1712141559	Time spent: 4
c.y.e.d.jpql.query.DefaultQueryLogger    : Query Hash: 1381068225	HQL Query: SELECT COUNT(DISTINCT user_entity_User)  FROM user.entity.User AS user_entity_User    WHERE (LOWER(user_entity_User.givenName) LIKE CONCAT('%', CONCAT(LOWER(:givenName_14ceb603_0), '%')) AND (1 = 1))
c.yahoo.elide.core.utils.TimedFunction   : Query Hash: 1381068225	Time spent: 1
```

# Elide 7
## Elide Configuration
Implement JsonApiSettingsBuilder bean

```
@Configuration
public class ElideConfig {
  @Bean
  JsonApiSettingsBuilderCustomizer getJsonApiSettingsBuilder(EntityDictionary entityDictionary) {
    return builder ->
        builder
            .updateStatus200()
            .joinFilterDialect(
                new RSQLFilterDialect(
                    entityDictionary, new CaseSensitivityStrategy.FIQLCompliant(), Boolean.TRUE))
            .subqueryFilterDialect(
                new RSQLFilterDialect(
                    entityDictionary, new CaseSensitivityStrategy.FIQLCompliant(), Boolean.TRUE));
  }
}
```


## User's given name = 'Justin'
### /user?filter=(givenName==%27*Justin*%27)

Record is successfully returned

```
// Log
c.y.e.d.jpql.query.DefaultQueryLogger    : Query Hash: 457705325	HQL Query: SELECT user_entity_User FROM user.entity.User AS user_entity_User    WHERE (user_entity_User.givenName LIKE CONCAT('%', CONCAT(:givenName_1a2ace7f_0, '%')) AND (1 = 1))  order by user_entity_User.updatedAt desc
c.yahoo.elide.core.utils.TimedFunction   : Query Hash: 457705325	Time spent: 26
c.y.e.d.jpql.query.DefaultQueryLogger    : Query Hash: 1680203496	HQL Query: SELECT COUNT(DISTINCT  user_entity_User)  FROM user.entity.User AS user_entity_User    WHERE (user_entity_User.givenName LIKE CONCAT('%', CONCAT(:givenName_1a2ace7f_0, '%')) AND (1 = 1))
c.yahoo.elide.core.utils.TimedFunction   : Query Hash: 1680203496	Time spent: 5
```
### /user?filter=(givenName==%27*JUSTIN*%27)

No records are returned

```
// Log
c.y.e.d.jpql.query.DefaultQueryLogger    : Query Hash: 28692902	HQL Query: SELECT user_entity_User FROM user.entity.User AS user_entity_User    WHERE (user_entity_User.givenName LIKE CONCAT('%', CONCAT(:givenName_d4e29e1f_0, '%')) AND (1 = 1))  order by user_entity_User.updatedAt desc
c.yahoo.elide.core.utils.TimedFunction   : Query Hash: 28692902	Time spent: 2
```

**Comment by justin-tay** [comment]
I think there is a rather subtle change in the configuration in Elide 7 in that the customizer allows you to override the defaults and there already is a default dialect using the `UseColumnCollation` `CaseSensitivityStrategy` that was defined first in the list that you would need to remove. Could you try again with the following?

```java
	@Bean
	JsonApiSettingsBuilderCustomizer getJsonApiSettingsBuilder(EntityDictionary entityDictionary) {
		return builder -> builder.updateStatus200()
				.joinFilterDialects(joinFilterDialects -> {
					joinFilterDialects.clear();
					joinFilterDialects.add(new RSQLFilterDialect(entityDictionary,
							new CaseSensitivityStrategy.FIQLCompliant(), Boolean.TRUE));
				})
				.subqueryFilterDialects(subqueryFilterDialects -> {
					subqueryFilterDialects.clear();
					subqueryFilterDialects.add(new RSQLFilterDialect(entityDictionary,
							new CaseSensitivityStrategy.FIQLCompliant(), Boolean.TRUE));
				});
	}
```

**Comment by white3km** [comment]
Awesome, that worked with Elide 7. Thank you so much for investigating and helping me get this fixed!
