### ISSUE TITLE
Throwing ServerErrorException causes ClassNotFoundException

### ISSUE THREAD

**Issue by micheljung** [yahoo/elide#581]
If, for instance, a JPA entity does not match the underlying database a `java.sql.SQLSyntaxErrorException` is thrown. This exception is handled by:

```
    private static RuntimeException handleInvocationTargetException(InvocationTargetException e) {
        Throwable exception = e.getTargetException();
        if (exception instanceof HttpStatusException || exception instanceof WebApplicationException) {
            return (RuntimeException) exception;
        }
        log.debug("Caught an unexpected exception (rethrowing as internal server error)", e);
        return new ServerErrorException("Unexpected exception caught", Response.Status.INTERNAL_SERVER_ERROR, e);
    }
```

If the application has a dependency to `org.glassfish.jersey.core:jersey-common`, this results in the following response:

```
{"errors":[{"status":"500","title":"javax.ws.rs.ServerErrorException","detail":"Unexpected exception caught"}]}
```

If not, constructing a `ServerErrorException` causes:

```
Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: org.glassfish.jersey.internal.RuntimeDelegateImpl
	at javax.ws.rs.ext.RuntimeDelegate.findDelegate(RuntimeDelegate.java:152)
	at javax.ws.rs.ext.RuntimeDelegate.getInstance(RuntimeDelegate.java:120)
	at javax.ws.rs.core.Response$ResponseBuilder.newInstance(Response.java:848)
	at javax.ws.rs.core.Response.status(Response.java:590)
	at javax.ws.rs.core.Response.status(Response.java:601)
	at javax.ws.rs.ServerErrorException.<init>(ServerErrorException.java:158)
	at com.yahoo.elide.core.PersistentResource.handleInvocationTargetException(PersistentResource.java:1914)
	at com.yahoo.elide.core.PersistentResource.getValue(PersistentResource.java:1618)
	at com.yahoo.elide.datastores.hibernate5.HibernateTransaction.getRelation(HibernateTransaction.java:191)
	at com.yahoo.elide.core.PersistentResource.getRelationUnchecked(PersistentResource.java:1022)
	at com.yahoo.elide.core.PersistentResource.getRelation(PersistentResource.java:886)
	at com.yahoo.elide.core.PersistentResource.getRelationCheckedFiltered(PersistentResource.java:863)
	at com.yahoo.elide.core.PersistentResource.getRelationshipsWithRelationshipFunction(PersistentResource.java:1271)
	at com.yahoo.elide.core.PersistentResource.getRelationships(PersistentResource.java:1245)
	at com.yahoo.elide.core.PersistentResource.toResource(PersistentResource.java:1234)
	at com.yahoo.elide.core.PersistentResource.toResource(PersistentResource.java:1211)
	at com.yahoo.elide.jsonapi.document.processors.IncludedProcessor.lambda$addResourcesForPath$3(IncludedProcessor.java:81)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at com.yahoo.elide.jsonapi.document.processors.IncludedProcessor.addResourcesForPath(IncludedProcessor.java:80)
	at com.yahoo.elide.jsonapi.document.processors.IncludedProcessor.lambda$null$1(IncludedProcessor.java:65)
	at java.util.Arrays$ArrayList.forEach(Arrays.java:3880)
	at com.yahoo.elide.jsonapi.document.processors.IncludedProcessor.lambda$addIncludedResources$2(IncludedProcessor.java:63)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at com.yahoo.elide.jsonapi.document.processors.IncludedProcessor.addIncludedResources(IncludedProcessor.java:60)
	at com.yahoo.elide.jsonapi.document.processors.IncludedProcessor.lambda$execute$0(IncludedProcessor.java:50)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at com.yahoo.elide.jsonapi.document.processors.IncludedProcessor.execute(IncludedProcessor.java:49)
	at com.yahoo.elide.parsers.state.CollectionTerminalState.handleGet(CollectionTerminalState.java:72)
	at com.yahoo.elide.parsers.state.StateContext.handleGet(StateContext.java:110)
	at com.yahoo.elide.parsers.GetVisitor.visitQuery(GetVisitor.java:34)
	at com.yahoo.elide.parsers.GetVisitor.visitQuery(GetVisitor.java:21)
	at com.yahoo.elide.generated.parsers.CoreParser$QueryContext.accept(CoreParser.java:558)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46)
	at com.yahoo.elide.generated.parsers.CoreBaseVisitor.visitStart(CoreBaseVisitor.java:20)
	at com.yahoo.elide.parsers.BaseVisitor.visitStart(BaseVisitor.java:47)
	at com.yahoo.elide.parsers.BaseVisitor.visitStart(BaseVisitor.java:33)
	at com.yahoo.elide.generated.parsers.CoreParser$StartContext.accept(CoreParser.java:107)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
	at com.yahoo.elide.Elide.lambda$get$0(Elide.java:90)
	at com.yahoo.elide.Elide.handleRequest(Elide.java:202)
	at com.yahoo.elide.Elide.get(Elide.java:85)
```

And the original exception is lost.

**Comment by DennisMcWherter** [comment]
To me, this seems to be a problem in the fact that we're not logging a subset of 500 response codes. The original exception isn't lost in the code (it should be attached as the `cause`), but it is certainly lost in the response from the `.toString()` like you mentioned.

Does this PR look sufficient to solve the issue you're encountering? https://github.com/yahoo/elide/pull/586

Basically, before the exception is thrown, we'll log it as an `error`. This should capture the cause as well.

**Comment by clayreimann** [comment]
@DennisMcWherter It seems to me that we shouldn't be trying to throw an error that the application may or may not know how to handle when we have a perfectly suitable exception that we can throw and deal with.

**Comment by DennisMcWherter** [comment]
Agreed. We should also improve the logging though :)

**Comment by micheljung** [comment]
> The original exception isn't lost in the code
If your error-handling code runs into a `ClassNotFoundException` then yes, your original exception is lost :)
Logging helps, yes, but IMO jax-rs should either be a dependency or it shouldn't be used

**Comment by clayreimann** [comment]
You’re right, and I fixed this in both the 3.x and 4.x lines. We might not have released it yet though

**Comment by DennisMcWherter** [comment]
3.2.1 has now been released. Please feel free to reopen if this issue persists. Thanks!

**Comment by rdp** [comment]
Is there a commit that fixed this?  Thanks!

**Comment by aklish** [comment]
Here is the fix:
https://github.com/yahoo/elide/blob/master/elide-core/src/main/java/com/yahoo/elide/core/EntityDictionary.java#L1439

Commit will be a bit harder to track down as the code has moved around from some refactoring.
