### ISSUE TITLE
c.y.e.security.FilterExpressionCheck: Failed to apply predicate on Collections

### ISSUE THREAD

**Issue by dotjim** [yahoo/elide#683]
> c.y.e.security.FilterExpressionCheck: Failed to apply predicate parent.children.userId IN [1]
>
> java.lang.IllegalArgumentException: Unknown Entity class org.hibernate.collection.internal.PersistentBag

The above is being thrown when a `FilterExpressionCheck` is used on a `@OneToMany` relationship. 

Interestingly the `FilterExpressionCheck` is invoked twice for each request cycle.  Once to influence the underlying database query which correctly includes the `FilterExpressionCheck` addition to prevent unnecessary result data, then a second time after the result has been retrieved from the database.

It's this second check that throws the exception, as in this case the `FilterExpressionCheck` is referencing lazy collection data that was not requested from the database, forcing Hibernate to try and lazily hydrate to a `PersistentBag`.

The documentation suggests the purpose of the `FilterExpressionCheck` is where:

> the check logic can be pushed down to the data store itself

Should this second assertion of `FilterExpressionCheck` occur?  It seems erroneous when the purpose over an `InlineCheck` is to avoid bringing back unnecessary data from the database to evaluate in memory?  

Is there any way to prevent this second `FilterExpressionCheck` check, or otherwise avoid this issue?

Full stack trace and setup below for context:

```
elideVersion=4.2.4
springBootVersion=2.0.3.RELEASE
hibernateVersion=5.2.15.Final
mysqlConnectorVersion=6.0.5
```

```
2018-07-30 15:07:15.352 ERROR 1947 --- [nio-8080-exec-1] c.y.e.security.FilterExpressionCheck     : Failed to apply predicate parent.children.userId IN [1]

java.lang.IllegalArgumentException: Unknown Entity class org.hibernate.collection.internal.PersistentBag
	at com.yahoo.elide.core.EntityDictionary.lookupEntityClass(EntityDictionary.java:952) ~[elide-core-4.2.4.jar:na]
	at com.yahoo.elide.core.EntityDictionary.getEntityBinding(EntityDictionary.java:142) ~[elide-core-4.2.4.jar:na]
	at com.yahoo.elide.core.EntityDictionary.getAccessibleObject(EntityDictionary.java:974) ~[elide-core-4.2.4.jar:na]
	at com.yahoo.elide.core.EntityDictionary.getAccessibleObject(EntityDictionary.java:963) ~[elide-core-4.2.4.jar:na]
	at com.yahoo.elide.core.PersistentResource.getValue(PersistentResource.java:1633) ~[elide-core-4.2.4.jar:na]
	at com.yahoo.elide.core.filter.Operator.getFieldValue(Operator.java:310) ~[elide-core-4.2.4.jar:na]
	at com.yahoo.elide.core.filter.Operator.lambda$in$2(Operator.java:183) ~[elide-core-4.2.4.jar:na]
	at com.yahoo.elide.security.FilterExpressionCheck.applyPredicateToObject(FilterExpressionCheck.java:72) [elide-core-4.2.4.jar:na]
	at com.yahoo.elide.parsers.expression.FilterExpressionCheckEvaluationVisitor.visitPredicate(FilterExpressionCheckEvaluationVisitor.java:37) [elide-core-4.2.4.jar:na]
	at com.yahoo.elide.parsers.expression.FilterExpressionCheckEvaluationVisitor.visitPredicate(FilterExpressionCheckEvaluationVisitor.java:23) [elide-core-4.2.4.jar:na]
	at com.yahoo.elide.core.filter.FilterPredicate.accept(FilterPredicate.java:133) [elide-core-4.2.4.jar:na]
	at com.yahoo.elide.security.FilterExpressionCheck.ok(FilterExpressionCheck.java:56) [elide-core-4.2.4.jar:na]
	at com.yahoo.elide.security.permissions.expressions.CheckExpression.computeCheck(CheckExpression.java:114) [elide-core-4.2.4.jar:na]
	at com.yahoo.elide.security.permissions.expressions.CheckExpression.evaluate(CheckExpression.java:98) [elide-core-4.2.4.jar:na]
	at com.yahoo.elide.security.permissions.expressions.AndExpression.evaluate(AndExpression.java:41) [elide-core-4.2.4.jar:na]
	at com.yahoo.elide.security.permissions.expressions.AnyFieldExpression.evaluate(AnyFieldExpression.java:42) [elide-core-4.2.4.jar:na]
	at com.yahoo.elide.security.executors.ActivePermissionExecutor.executeExpressions(ActivePermissionExecutor.java:399) [elide-core-4.2.4.jar:na]
	at com.yahoo.elide.security.executors.ActivePermissionExecutor.lambda$checkPermission$1(ActivePermissionExecutor.java:130) [elide-core-4.2.4.jar:na]
	at com.yahoo.elide.security.executors.ActivePermissionExecutor.lambda$checkPermissions$7(ActivePermissionExecutor.java:297) [elide-core-4.2.4.jar:na]
	at java.util.Optional.map(Optional.java:215) ~[na:1.8.0_172]
	at com.yahoo.elide.security.executors.ActivePermissionExecutor.checkPermissions(ActivePermissionExecutor.java:297) [elide-core-4.2.4.jar:na]
	at com.yahoo.elide.security.executors.ActivePermissionExecutor.checkPermissions(ActivePermissionExecutor.java:343) [elide-core-4.2.4.jar:na]
	at com.yahoo.elide.security.executors.ActivePermissionExecutor.checkPermission(ActivePermissionExecutor.java:133) [elide-core-4.2.4.jar:na]
	at com.yahoo.elide.security.executors.ActivePermissionExecutor.checkPermission(ActivePermissionExecutor.java:95) [elide-core-4.2.4.jar:na]
	at com.yahoo.elide.core.PersistentResource.checkFieldAwarePermissions(PersistentResource.java:1810) ~[elide-core-4.2.4.jar:na]
	at com.yahoo.elide.core.PersistentResource.filter(PersistentResource.java:1769) ~[elide-core-4.2.4.jar:na]
	at com.yahoo.elide.core.PersistentResource.getRelationCheckedFiltered(PersistentResource.java:913) ~[elide-core-4.2.4.jar:na]
	at com.yahoo.elide.core.PersistentResource.lambda$getRelationships$21(PersistentResource.java:1257) ~[elide-core-4.2.4.jar:na]
	at com.yahoo.elide.core.PersistentResource.getRelationshipsWithRelationshipFunction(PersistentResource.java:1290) ~[elide-core-4.2.4.jar:na]
	at com.yahoo.elide.core.PersistentResource.getRelationships(PersistentResource.java:1255) ~[elide-core-4.2.4.jar:na]
	at com.yahoo.elide.core.PersistentResource.toResource(PersistentResource.java:1244) ~[elide-core-4.2.4.jar:na]
	at com.yahoo.elide.core.PersistentResource.toResource(PersistentResource.java:1221) ~[elide-core-4.2.4.jar:na]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[na:1.8.0_172]
	at java.util.Iterator.forEachRemaining(Iterator.java:116) ~[na:1.8.0_172]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[na:1.8.0_172]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[na:1.8.0_172]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[na:1.8.0_172]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[na:1.8.0_172]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:1.8.0_172]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[na:1.8.0_172]
	at com.yahoo.elide.parsers.state.CollectionTerminalState.getData(CollectionTerminalState.java:154) ~[elide-core-4.2.4.jar:na]
	at com.yahoo.elide.parsers.state.CollectionTerminalState.handleGet(CollectionTerminalState.java:71) ~[elide-core-4.2.4.jar:na]
	at com.yahoo.elide.parsers.state.StateContext.handleGet(StateContext.java:110) ~[elide-core-4.2.4.jar:na]
	at com.yahoo.elide.parsers.GetVisitor.visitQuery(GetVisitor.java:34) ~[elide-core-4.2.4.jar:na]
	at com.yahoo.elide.parsers.GetVisitor.visitQuery(GetVisitor.java:21) ~[elide-core-4.2.4.jar:na]
	at com.yahoo.elide.generated.parsers.CoreParser$QueryContext.accept(CoreParser.java:558) ~[elide-core-4.2.4.jar:na]
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46) ~[antlr4-runtime-4.6.jar:4.6]
	at com.yahoo.elide.generated.parsers.CoreBaseVisitor.visitStart(CoreBaseVisitor.java:20) ~[elide-core-4.2.4.jar:na]
	at com.yahoo.elide.parsers.BaseVisitor.visitStart(BaseVisitor.java:47) ~[elide-core-4.2.4.jar:na]
	at com.yahoo.elide.parsers.BaseVisitor.visitStart(BaseVisitor.java:33) ~[elide-core-4.2.4.jar:na]
	at com.yahoo.elide.generated.parsers.CoreParser$StartContext.accept(CoreParser.java:107) ~[elide-core-4.2.4.jar:na]
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18) ~[antlr4-runtime-4.6.jar:4.6]
	at com.yahoo.elide.Elide.lambda$get$0(Elide.java:86) ~[elide-core-4.2.4.jar:na]
	at com.yahoo.elide.Elide.handleRequest(Elide.java:198) ~[elide-core-4.2.4.jar:na]
	at com.yahoo.elide.Elide.get(Elide.java:81) ~[elide-core-4.2.4.jar:na]
```
Test entities to illustrate the issue:

```java
@Entity
@ReadPermission(expression = "is accessed by owner at operation")
@Include(rootLevel = true)
public class Parent implements Serializable {
    private static final long serialVersionUID = 1L;
    private Long id;
    private Collection<Child> children = new ArrayList<>();

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "parent_id", unique = true, nullable = false)
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @OneToMany(mappedBy = "parent", fetch = FetchType.EAGER)
    @JsonManagedReference
    public Collection<Child> getChildren() {
        return children;
    }

    public void setChildren(Collection<Children> children) {
        this.children = children;
    }

    static public class IsOwnedByUser extends FilterExpressionCheck<Parent> {
        @Override
        public FilterExpression getFilterExpression(Class<?> entityClass, RequestScope requestScope) {
            Long currentUserId = OwnedEntityChecks.getUserId(requestScope);

            Path.PathElement childPath = new Path.PathElement(Parent.class, Child.class, "children");
            Path.PathElement userIdPath = new Path.PathElement(Child.class, Long.class, "userId");

            Path path = new Path(Arrays.asList(childPath, userIdPath));
            return new FilterPredicate(path, Operator.IN, Collections.singletonList(currentUserId));
        }
    }
}

@Entity
@ReadPermission(expression = "Prefab.Role.All")
@Include(rootLevel = true)
public class Child implements Serializable {
    private static final long serialVersionUID = 1L;
    private Long id;
    private Long userId;
    private Parent parent;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "child_id", unique = true, nullable = false)
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "parent_id", nullable = true)
    public Parent getParent() {
        return this.parent;
    }

    public void setParent(Parent parent) {
        this.parent = parent;
    }
}
```

**Comment by aklish** [comment]
So here is the underlying issue.  Elide is currently expecting the path of the filter predicate to traverse toOne relationships only.  You can see this assumption in the in-memory Evaluation of the IN operator:

`getFieldValue` is navigating the path ("children.userId") from parent and extracting the singular value it expects to use in the IN clause (the lvalue of the IN operator):

```    private static <T> Object getFieldValue(T entity, String fieldPath, RequestScope requestScope) {
        Object val = entity;
        for (String field : fieldPath.split("\\.")) {
            if ("this".equals(field)) {
                continue;
            }
            val = PersistentResource.getValue(val, field, requestScope);
        }
        return val;
    }```

The IN operator uses this singular value to compare with the list of comparison objects (the RVALUE of the IN clause).

```    // In with strict equality
    private static <T> Predicate<T> in(String field, List<Object> values, RequestScope requestScope) {
        return (T entity) -> {
            Object val = getFieldValue(entity, field, requestScope);

            return val != null && values.stream()
                    .map(v -> CoerceUtil.coerce(v, val.getClass()))
                    .anyMatch(val::equals);
        };
    }```

So the in memory code could be adjusted to account for collections that would be returned along the path in the filter expression.  I'm not 100% certain this will work in all cases in Hibernate.  

However, it is probably worth experimenting with.

**Comment by thaingo** [comment]
@wcekan Might I know if any progress on this? Thanks.

**Comment by wcekan** [comment]
Trying to handle the FilterExpressionPath for collections in the paths similarly how we enforce ReadPermission for filter expression fields. Will update when I have a solution.
