### ISSUE TITLE
server start or run error

### ISSUE THREAD

**Issue by tbo-axelor** [yahoo/elide#687]
when start or run then give error like 

```
18:43:36.790 [main] WARN org.reflections.Reflections - could not create Dir using jarFile from url file:/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.172-9.b11.fc28.x86_64/jre/lib/ext/java-atk-wrapper.jar. skipping.
java.lang.NullPointerException: null
	at java.util.zip.ZipFile.<init>(ZipFile.java:213)
	at java.util.zip.ZipFile.<init>(ZipFile.java:155)
	at java.util.jar.JarFile.<init>(JarFile.java:166)
	at java.util.jar.JarFile.<init>(JarFile.java:130)
	at org.reflections.vfs.Vfs$DefaultUrlTypes$1.createDir(Vfs.java:216)
	at org.reflections.vfs.Vfs.fromURL(Vfs.java:99)
	at org.reflections.vfs.Vfs.fromURL(Vfs.java:91)
	at org.reflections.Reflections.scan(Reflections.java:240)
	at org.reflections.Reflections.scan(Reflections.java:202)
	at org.reflections.Reflections.<init>(Reflections.java:123)
	at com.yahoo.elide.standalone.Util.getAllEntities(Util.java:54)
	at com.yahoo.elide.standalone.config.ElideResourceConfig$1.configure(ElideResourceConfig.java:51)
	at org.glassfish.jersey.internal.inject.AbstractBinder.invokeConfigure(AbstractBinder.java:280)
	at org.glassfish.jersey.internal.inject.AbstractBinder.getBindings(AbstractBinder.java:270)
	at org.glassfish.jersey.internal.inject.Bindings.getBindings(Bindings.java:68)
	at org.glassfish.jersey.internal.inject.AbstractBinder.lambda$getBindings$1(AbstractBinder.java:272)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:267)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at org.glassfish.jersey.internal.inject.AbstractBinder.getBindings(AbstractBinder.java:273)
	at org.glassfish.jersey.internal.inject.Bindings.getBindings(Bindings.java:68)
	at org.glassfish.jersey.inject.hk2.Hk2Helper.bind(Hk2Helper.java:90)
	at org.glassfish.jersey.inject.hk2.ImmediateHk2InjectionManager.register(ImmediateHk2InjectionManager.java:82)
	at org.glassfish.jersey.model.internal.CommonConfig.configureBinders(CommonConfig.java:647)
	at org.glassfish.jersey.model.internal.CommonConfig.configureMetaProviders(CommonConfig.java:628)
	at org.glassfish.jersey.server.ResourceConfig.configureMetaProviders(ResourceConfig.java:823)
	at org.glassfish.jersey.server.ApplicationHandler.initialize(ApplicationHandler.java:351)
	at org.glassfish.jersey.server.ApplicationHandler.lambda$initialize$1(ApplicationHandler.java:316)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:316)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:298)
	at org.glassfish.jersey.internal.Errors.processWithException(Errors.java:256)
	at org.glassfish.jersey.server.ApplicationHandler.initialize(ApplicationHandler.java:315)
	at org.glassfish.jersey.server.ApplicationHandler.<init>(ApplicationHandler.java:282)
	at org.glassfish.jersey.servlet.WebComponent.<init>(WebComponent.java:335)
	at org.glassfish.jersey.servlet.ServletContainer.init(ServletContainer.java:178)
	at org.glassfish.jersey.servlet.ServletContainer.init(ServletContainer.java:370)
	at javax.servlet.GenericServlet.init(GenericServlet.java:244)
	at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:643)
	at org.eclipse.jetty.servlet.ServletHolder.initialize(ServletHolder.java:422)
	at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:892)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:349)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:778)
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:262)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
	at org.eclipse.jetty.server.Server.start(Server.java:422)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:105)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.server.Server.doStart(Server.java:389)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at com.yahoo.elide.standalone.ElideStandalone.start(ElideStandalone.java:100)
	at com.axelor.repository.Main.main(Main.java:21)
18:43:36.792 [main] WARN org.reflections.Reflections - could not create Vfs.Dir from url. ignoring the exception and continuing
org.reflections.ReflectionsException: Could not open url connection
	at org.reflections.vfs.JarInputDir$1$1.<init>(JarInputDir.java:37)
	at org.reflections.vfs.JarInputDir$1.iterator(JarInputDir.java:33)
	at org.reflections.Reflections.scan(Reflections.java:243)
	at org.reflections.Reflections.scan(Reflections.java:202)
	at org.reflections.Reflections.<init>(Reflections.java:123)
	at com.yahoo.elide.standalone.Util.getAllEntities(Util.java:54)
	at com.yahoo.elide.standalone.config.ElideResourceConfig$1.configure(ElideResourceConfig.java:51)
	at org.glassfish.jersey.internal.inject.AbstractBinder.invokeConfigure(AbstractBinder.java:280)
	at org.glassfish.jersey.internal.inject.AbstractBinder.getBindings(AbstractBinder.java:270)
	at org.glassfish.jersey.internal.inject.Bindings.getBindings(Bindings.java:68)
	at org.glassfish.jersey.internal.inject.AbstractBinder.lambda$getBindings$1(AbstractBinder.java:272)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:267)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at org.glassfish.jersey.internal.inject.AbstractBinder.getBindings(AbstractBinder.java:273)
	at org.glassfish.jersey.internal.inject.Bindings.getBindings(Bindings.java:68)
	at org.glassfish.jersey.inject.hk2.Hk2Helper.bind(Hk2Helper.java:90)
	at org.glassfish.jersey.inject.hk2.ImmediateHk2InjectionManager.register(ImmediateHk2InjectionManager.java:82)
	at org.glassfish.jersey.model.internal.CommonConfig.configureBinders(CommonConfig.java:647)
	at org.glassfish.jersey.model.internal.CommonConfig.configureMetaProviders(CommonConfig.java:628)
	at org.glassfish.jersey.server.ResourceConfig.configureMetaProviders(ResourceConfig.java:823)
	at org.glassfish.jersey.server.ApplicationHandler.initialize(ApplicationHandler.java:351)
	at org.glassfish.jersey.server.ApplicationHandler.lambda$initialize$1(ApplicationHandler.java:316)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:316)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:298)
	at org.glassfish.jersey.internal.Errors.processWithException(Errors.java:256)
	at org.glassfish.jersey.server.ApplicationHandler.initialize(ApplicationHandler.java:315)
	at org.glassfish.jersey.server.ApplicationHandler.<init>(ApplicationHandler.java:282)
	at org.glassfish.jersey.servlet.WebComponent.<init>(WebComponent.java:335)
	at org.glassfish.jersey.servlet.ServletContainer.init(ServletContainer.java:178)
	at org.glassfish.jersey.servlet.ServletContainer.init(ServletContainer.java:370)
	at javax.servlet.GenericServlet.init(GenericServlet.java:244)
	at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:643)
	at org.eclipse.jetty.servlet.ServletHolder.initialize(ServletHolder.java:422)
	at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:892)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:349)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:778)
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:262)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
	at org.eclipse.jetty.server.Server.start(Server.java:422)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:105)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.server.Server.doStart(Server.java:389)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at com.yahoo.elide.standalone.ElideStandalone.start(ElideStandalone.java:100)
	at com.axelor.repository.Main.main(Main.java:21)
Caused by: java.io.FileNotFoundException: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.172-9.b11.fc28.x86_64/jre/lib/ext/java-atk-wrapper.jar (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:90)
	at sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:188)
	at org.reflections.vfs.JarInputDir$1$1.<init>(JarInputDir.java:36)
	... 50 common frames omitted
```

you can clone https://github.com/tbo-axelor/elide-graphql-demo.git and debug locally
so please help me as soon as possible

**Comment by aklish** [comment]
I didn't run the project, but line 13 is commented out and is what you want:
https://github.com/tbo-axelor/elide-graphql-demo/blob/master/src/main/java/com/axelor/repository/Settings.java#L13

Line 12 (the current line) has the wrong package name for your models.

**Comment by clayreimann** [comment]
I've opened https://github.com/tbo-axelor/elide-graphql-demo/pull/1 which makes everything run as expected.

**Comment by tbo-axelor** [comment]
yes,everything is run as expected but above error display in console.

**Comment by clayreimann** [comment]
How are you starting your application? It works fine when I run the `Main` class from IntelliJ. I just noticed that the `mainClassName` in your `build.gradle` has the wrong path

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
