### ISSUE TITLE
Throwing exception causes "Transaction not closed"

### ISSUE THREAD

**Issue by DerKlassiker** [yahoo/elide#699]
I made a customized DataStoreTransaction that implements DataStoreTransaction. 

In public Iterable<Object> loadObjects(...) method, I throw 

Response response = Response.status(Status.NOT_FOUND).entity("Resource not found").build();
throw new NotFoundException("error message", response);

But when this exception was thrown, I got this error message 

Suppressed: java.io.IOException: Transaction not closed
		at com.yahoo.elide.datastores.hibernate5.HibernateTransaction.close(HibernateTransaction.java:271)
		at com.yahoo.elide.datastores.multiplex.MultiplexTransaction.close(MultiplexTransaction.java:118)
		at com.yahoo.elide.Elide.handleRequest(Elide.java:228)

and it eventually returns 500, not 404. 

How can I return 404 properly?

**Comment by aklish** [comment]
If you want to control the HTTP status code the service returns from anywhere within your extension code (life cycle hooks, data stores, etc), throw a subclass of `HttpStatusException` (an elide class - there are at least a dozen of them).

Here is an example of that in the HibernateTransaction code:
https://github.com/yahoo/elide/blob/master/elide-datastore/elide-datastore-hibernate5/src/main/java/com/yahoo/elide/datastores/hibernate5/HibernateTransaction.java#L91

**Comment by aklish** [comment]
Closing for inactivity.  Reopen if this is still an issue.
