### ISSUE TITLE
GraphQL Entity with field level annotation is throwing exception

### ISSUE THREAD

**Issue by bappajubcse05** [yahoo/elide#709]
I have created a graphQL entity (**version: 4.2.0**) and applied the annotation at the field level, but when I am trying to deploy the application, it is throwing error -
```
Caused by: graphql.AssertException: Name must be non-null, non-empty and match [_A-Za-z][_0-9A-Za-z]*
                 | 	at graphql.Assert.assertValidName(Assert.java:54) ~[graphql-java-6.0.jar!/:na]
                 | 	at graphql.schema.GraphQLInputObjectField.<init>(GraphQLInputObjectField.java:42) ~[graphql-java-6.0.jar!/:na]
```
Attached the complete exception logs. [exception.log](https://github.com/yahoo/elide/files/2438322/exception.log)
Code:

```
@Entity
@Getter
@Setter
@EqualsAndHashCode(of = "id")
@ToString
public class Car implements Persistable<UUID> {
    @Id
    @Type(type = "uuid-char")
    @GeneratedValue
    private UUID id;

    @Size(max = 50)
    private String name;

    @Max(30)
    private int model;

    @Override
    @Transient
    public boolean isNew() {
        return id == null;
    }
}
```

It is working fine when the annotation is applied at Getter method.
Code:

```
@Entity
@Getter
@Setter
@EqualsAndHashCode(of = "id")
@ToString
public class Car implements Persistable<UUID> {
    private UUID id;

    @Size(max = 50)
    private String name;

    @Max(30)
    private int model;

    @Override
    @Transient
    public boolean isNew() {
        return id == null;
    }

    @Id
    @Type(type = "uuid-char")
    @GeneratedValue
    public UUID getId() {
        return id;
    }
}
```

**Comment by aklish** [comment]
You need Elide 4.2.7 or later to expose data through JPA fields (instead of properties).  Can you try the latest and see if that fixes your issue?

**Comment by DennisMcWherter** [comment]
Hi @bappajubcse05 did upgrading fix your issue?

**Comment by DennisMcWherter** [comment]
Closing due to inactivity. Presumably this has been resolved by upgrade. Please reopen if this is still an issue.
