### ISSUE TITLE
UnsupportedOperationException on PATCH request

### ISSUE THREAD

**Issue by leon972** [yahoo/elide#743]
I can successfully POST the following object 
{"data":{"type":"user","attributes":{"costCenterManager":true,"admin":false,"email":"piretti@gmail.com","domainAccount":null,"name":"Test user"}}}
but when I try to modify it using PATCH and sending the same object after adding the id in this way:
{"data":{"type":"user","id":22,"attributes":{"costCenterManager":true,"admin":false,"email":"piretti@gmail.com","domainAccount":null,"name":"Test user"}}} 
I get this error:

Error or exception uncaught by Elide
java.lang.UnsupportedOperationException: class com.yahoo.elide.parsers.state.CollectionTerminalState
	at com.yahoo.elide.parsers.state.BaseState.handlePatch(BaseState.java:141)
	at com.yahoo.elide.parsers.state.StateContext.handlePatch(StateContext.java:115)
	at com.yahoo.elide.parsers.PatchVisitor.visitQuery(PatchVisitor.java:33)
	at com.yahoo.elide.parsers.PatchVisitor.visitQuery(PatchVisitor.java:20)
	at com.yahoo.elide.generated.parsers.CoreParser$QueryContext.accept(CoreParser.java:558)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46)
	at com.yahoo.elide.generated.parsers.CoreBaseVisitor.visitStart(CoreBaseVisitor.java:20)
	at com.yahoo.elide.parsers.BaseVisitor.visitStart(BaseVisitor.java:49)
	at com.yahoo.elide.parsers.BaseVisitor.visitStart(BaseVisitor.java:35)
	at com.yahoo.elide.generated.parsers.CoreParser$StartContext.accept(CoreParser.java:107)
	Suppressed: java.io.IOException: Transaction not closed

I am using Elide 4.2.12

**Comment by DennisMcWherter** [comment]
This exceptions looks to me like you're running a `PATCH` against the collection rather than the resource ([JSON-API requires you use the resource](https://jsonapi.org/format/#crud-updating)).

What URL are you running this query against?

**Comment by aklish** [comment]
Going to close this issue for inactivity.   Reopen with more info if this is still an issue.
